// Large trivia pool. Answer (a) is matched case-insensitively against one of the choices.
export interface TriviaQ { q: string; a: string; choices: string[] }

export const TRIVIA_QUESTIONS: TriviaQ[] = [
  // ===== Geography (60) =====
  { q: "Capital of Japan?", a: "tokyo", choices: ["Kyoto","Tokyo","Osaka","Seoul"] },
  { q: "Capital of France?", a: "paris", choices: ["Lyon","Paris","Nice","Marseille"] },
  { q: "Capital of Australia?", a: "canberra", choices: ["Sydney","Melbourne","Canberra","Perth"] },
  { q: "Capital of Canada?", a: "ottawa", choices: ["Toronto","Vancouver","Ottawa","Montreal"] },
  { q: "Capital of Brazil?", a: "brasilia", choices: ["Rio de Janeiro","São Paulo","Brasilia","Salvador"] },
  { q: "Capital of Egypt?", a: "cairo", choices: ["Alexandria","Cairo","Giza","Luxor"] },
  { q: "Capital of India?", a: "new delhi", choices: ["Mumbai","Kolkata","New Delhi","Chennai"] },
  { q: "Capital of South Korea?", a: "seoul", choices: ["Busan","Seoul","Incheon","Daegu"] },
  { q: "Capital of Russia?", a: "moscow", choices: ["St. Petersburg","Moscow","Kazan","Sochi"] },
  { q: "Capital of Germany?", a: "berlin", choices: ["Munich","Hamburg","Berlin","Frankfurt"] },
  { q: "Capital of Spain?", a: "madrid", choices: ["Barcelona","Madrid","Seville","Valencia"] },
  { q: "Capital of Italy?", a: "rome", choices: ["Milan","Rome","Naples","Turin"] },
  { q: "Capital of Greece?", a: "athens", choices: ["Athens","Thessaloniki","Patras","Sparta"] },
  { q: "Capital of Turkey?", a: "ankara", choices: ["Istanbul","Ankara","Izmir","Bursa"] },
  { q: "Capital of Argentina?", a: "buenos aires", choices: ["Córdoba","Buenos Aires","Rosario","Mendoza"] },
  { q: "Capital of Mexico?", a: "mexico city", choices: ["Guadalajara","Monterrey","Mexico City","Puebla"] },
  { q: "Capital of Thailand?", a: "bangkok", choices: ["Phuket","Bangkok","Chiang Mai","Pattaya"] },
  { q: "Capital of Vietnam?", a: "hanoi", choices: ["Ho Chi Minh City","Hanoi","Da Nang","Hue"] },
  { q: "Capital of Indonesia?", a: "jakarta", choices: ["Bali","Surabaya","Jakarta","Bandung"] },
  { q: "Capital of New Zealand?", a: "wellington", choices: ["Auckland","Wellington","Christchurch","Hamilton"] },
  { q: "Capital of South Africa (executive)?", a: "pretoria", choices: ["Cape Town","Johannesburg","Pretoria","Durban"] },
  { q: "Capital of Kenya?", a: "nairobi", choices: ["Mombasa","Nairobi","Kisumu","Nakuru"] },
  { q: "Capital of Nigeria?", a: "abuja", choices: ["Lagos","Abuja","Kano","Ibadan"] },
  { q: "Capital of Morocco?", a: "rabat", choices: ["Casablanca","Marrakech","Rabat","Fez"] },
  { q: "Capital of Saudi Arabia?", a: "riyadh", choices: ["Mecca","Jeddah","Riyadh","Medina"] },
  { q: "Capital of Iran?", a: "tehran", choices: ["Isfahan","Tehran","Shiraz","Tabriz"] },
  { q: "Capital of Pakistan?", a: "islamabad", choices: ["Karachi","Lahore","Islamabad","Peshawar"] },
  { q: "Capital of Bangladesh?", a: "dhaka", choices: ["Chittagong","Dhaka","Khulna","Sylhet"] },
  { q: "Capital of Philippines?", a: "manila", choices: ["Cebu","Manila","Davao","Quezon City"] },
  { q: "Capital of Malaysia?", a: "kuala lumpur", choices: ["Penang","Kuala Lumpur","Johor Bahru","Ipoh"] },
  { q: "Largest country by area?", a: "russia", choices: ["China","Russia","USA","Canada"] },
  { q: "Smallest country in the world?", a: "vatican city", choices: ["Monaco","Vatican City","Nauru","San Marino"] },
  { q: "Longest river in the world?", a: "nile", choices: ["Amazon","Nile","Yangtze","Mississippi"] },
  { q: "Largest desert in the world?", a: "antarctic", choices: ["Sahara","Gobi","Antarctic","Arabian"] },
  { q: "Highest mountain in the world?", a: "everest", choices: ["K2","Kangchenjunga","Everest","Makalu"] },
  { q: "Deepest ocean?", a: "pacific", choices: ["Atlantic","Indian","Pacific","Arctic"] },
  { q: "Largest ocean?", a: "pacific", choices: ["Atlantic","Indian","Pacific","Arctic"] },
  { q: "Smallest continent?", a: "australia", choices: ["Europe","Australia","Antarctica","South America"] },
  { q: "Which country has the most population?", a: "india", choices: ["China","India","USA","Indonesia"] },
  { q: "How many continents are there?", a: "7", choices: ["5","6","7","8"] },
  { q: "Which country is shaped like a boot?", a: "italy", choices: ["Spain","Italy","Greece","Portugal"] },
  { q: "What is the largest island in the world?", a: "greenland", choices: ["Australia","Greenland","New Guinea","Borneo"] },
  { q: "Which sea is the saltiest?", a: "dead sea", choices: ["Dead Sea","Red Sea","Caspian Sea","Black Sea"] },
  { q: "Mount Fuji is in which country?", a: "japan", choices: ["China","Japan","South Korea","Taiwan"] },
  { q: "The Eiffel Tower is in which city?", a: "paris", choices: ["London","Paris","Berlin","Rome"] },
  { q: "Big Ben is in which city?", a: "london", choices: ["London","Manchester","Edinburgh","Liverpool"] },
  { q: "The Great Wall is in which country?", a: "china", choices: ["Japan","China","Mongolia","Korea"] },
  { q: "The Taj Mahal is in which country?", a: "india", choices: ["Pakistan","India","Bangladesh","Nepal"] },
  { q: "The Pyramids of Giza are in which country?", a: "egypt", choices: ["Sudan","Egypt","Libya","Israel"] },
  { q: "Which river flows through London?", a: "thames", choices: ["Severn","Thames","Mersey","Tyne"] },
  { q: "Which river flows through Paris?", a: "seine", choices: ["Rhone","Loire","Seine","Garonne"] },
  { q: "Which river flows through Rome?", a: "tiber", choices: ["Po","Arno","Tiber","Adige"] },
  { q: "Which country has the most time zones?", a: "france", choices: ["Russia","France","USA","UK"] },
  { q: "What is the capital of Switzerland?", a: "bern", choices: ["Zurich","Geneva","Bern","Basel"] },
  { q: "Which country uses the yen?", a: "japan", choices: ["China","Japan","Korea","Thailand"] },
  { q: "What is the currency of the UK?", a: "pound", choices: ["Euro","Pound","Dollar","Krone"] },
  { q: "Which country's flag has a red maple leaf?", a: "canada", choices: ["USA","Canada","Lebanon","Mexico"] },
  { q: "What is the capital of Portugal?", a: "lisbon", choices: ["Porto","Lisbon","Braga","Faro"] },
  { q: "What is the capital of Norway?", a: "oslo", choices: ["Bergen","Oslo","Trondheim","Stavanger"] },
  { q: "What is the capital of Sweden?", a: "stockholm", choices: ["Gothenburg","Stockholm","Malmö","Uppsala"] },

  // ===== Science (60) =====
  { q: "Chemical symbol for Gold?", a: "au", choices: ["Au","Gd","Go","Ag"] },
  { q: "Chemical symbol for Silver?", a: "ag", choices: ["Si","Ag","Au","Sv"] },
  { q: "Chemical symbol for Iron?", a: "fe", choices: ["Ir","In","Fe","Fr"] },
  { q: "Chemical symbol for Sodium?", a: "na", choices: ["So","Na","Sd","S"] },
  { q: "Chemical symbol for Potassium?", a: "k", choices: ["P","Po","K","Pt"] },
  { q: "Chemical symbol for Mercury?", a: "hg", choices: ["Me","My","Hg","Mr"] },
  { q: "Chemical symbol for Lead?", a: "pb", choices: ["Ld","Le","Pb","Pl"] },
  { q: "Chemical symbol for Tin?", a: "sn", choices: ["Ti","Tn","Sn","Sm"] },
  { q: "Atomic number of Hydrogen?", a: "1", choices: ["1","2","3","8"] },
  { q: "Atomic number of Oxygen?", a: "8", choices: ["6","7","8","16"] },
  { q: "Atomic number of Carbon?", a: "6", choices: ["4","6","8","12"] },
  { q: "How many bones in the adult human body?", a: "206", choices: ["186","206","226","306"] },
  { q: "How many chambers does the human heart have?", a: "4", choices: ["2","3","4","6"] },
  { q: "Largest organ in the human body?", a: "skin", choices: ["Liver","Skin","Brain","Lungs"] },
  { q: "How many teeth does an adult human typically have?", a: "32", choices: ["28","30","32","36"] },
  { q: "What gas do plants absorb from the atmosphere?", a: "carbon dioxide", choices: ["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"] },
  { q: "What gas do humans exhale?", a: "carbon dioxide", choices: ["Oxygen","Carbon Dioxide","Hydrogen","Methane"] },
  { q: "What is the speed of light (approx)?", a: "300,000 km/s", choices: ["30,000 km/s","300,000 km/s","3,000,000 km/s","30,000,000 km/s"] },
  { q: "Largest planet in our solar system?", a: "jupiter", choices: ["Earth","Mars","Saturn","Jupiter"] },
  { q: "Smallest planet in our solar system?", a: "mercury", choices: ["Mercury","Mars","Pluto","Venus"] },
  { q: "Closest planet to the Sun?", a: "mercury", choices: ["Venus","Earth","Mercury","Mars"] },
  { q: "Red planet in our solar system?", a: "mars", choices: ["Venus","Mars","Jupiter","Mercury"] },
  { q: "Which planet has the most moons?", a: "saturn", choices: ["Jupiter","Saturn","Uranus","Neptune"] },
  { q: "How many planets are in our solar system?", a: "8", choices: ["7","8","9","10"] },
  { q: "Which planet is known for its rings?", a: "saturn", choices: ["Mars","Saturn","Jupiter","Neptune"] },
  { q: "Year humans first landed on the Moon?", a: "1969", choices: ["1965","1969","1972","1958"] },
  { q: "What is the hardest natural substance?", a: "diamond", choices: ["Iron","Quartz","Diamond","Granite"] },
  { q: "What is H2O commonly known as?", a: "water", choices: ["Salt","Water","Acid","Alcohol"] },
  { q: "What is the most abundant gas in Earth's atmosphere?", a: "nitrogen", choices: ["Oxygen","Nitrogen","Carbon Dioxide","Argon"] },
  { q: "Which scientist developed the theory of relativity?", a: "einstein", choices: ["Newton","Einstein","Tesla","Galileo"] },
  { q: "Who discovered penicillin?", a: "fleming", choices: ["Pasteur","Fleming","Curie","Darwin"] },
  { q: "Who proposed the theory of evolution by natural selection?", a: "darwin", choices: ["Darwin","Mendel","Wallace","Lamarck"] },
  { q: "What is the unit of electric current?", a: "ampere", choices: ["Volt","Watt","Ampere","Ohm"] },
  { q: "What is the unit of force?", a: "newton", choices: ["Joule","Newton","Pascal","Watt"] },
  { q: "What is the unit of energy?", a: "joule", choices: ["Watt","Joule","Volt","Newton"] },
  { q: "At what temperature does water boil (°C)?", a: "100", choices: ["90","95","100","110"] },
  { q: "At what temperature does water freeze (°C)?", a: "0", choices: ["-10","0","10","32"] },
  { q: "What is the chemical formula for table salt?", a: "nacl", choices: ["KCl","NaCl","CaCl","NaOH"] },
  { q: "How many colors are in a rainbow?", a: "7", choices: ["5","6","7","8"] },
  { q: "What is the largest mammal?", a: "blue whale", choices: ["Elephant","Blue Whale","Giraffe","Hippo"] },
  { q: "What is the fastest land animal?", a: "cheetah", choices: ["Lion","Cheetah","Horse","Gazelle"] },
  { q: "Which animal is known as the King of the Jungle?", a: "lion", choices: ["Tiger","Lion","Elephant","Leopard"] },
  { q: "How many legs does a spider have?", a: "8", choices: ["6","8","10","12"] },
  { q: "How many legs does an insect have?", a: "6", choices: ["4","6","8","10"] },
  { q: "Which bird is known for its colorful tail feathers?", a: "peacock", choices: ["Parrot","Peacock","Flamingo","Swan"] },
  { q: "What do bees produce?", a: "honey", choices: ["Wax","Honey","Milk","Silk"] },
  { q: "What do caterpillars become?", a: "butterflies", choices: ["Bees","Beetles","Butterflies","Moths only"] },
  { q: "What is the largest type of shark?", a: "whale shark", choices: ["Great White","Whale Shark","Tiger Shark","Hammerhead"] },
  { q: "Which dinosaur had three horns?", a: "triceratops", choices: ["T-Rex","Stegosaurus","Triceratops","Velociraptor"] },
  { q: "What part of the cell contains DNA?", a: "nucleus", choices: ["Membrane","Nucleus","Cytoplasm","Mitochondria"] },
  { q: "What is the powerhouse of the cell?", a: "mitochondria", choices: ["Nucleus","Mitochondria","Ribosome","Lysosome"] },
  { q: "What blood type is the universal donor?", a: "o negative", choices: ["A","AB positive","O negative","B negative"] },
  { q: "What vitamin does the sun give us?", a: "vitamin d", choices: ["Vitamin A","Vitamin C","Vitamin D","Vitamin K"] },
  { q: "What is the pH of pure water?", a: "7", choices: ["5","6","7","8"] },
  { q: "What galaxy do we live in?", a: "milky way", choices: ["Andromeda","Milky Way","Triangulum","Whirlpool"] },
  { q: "What force keeps us on the ground?", a: "gravity", choices: ["Magnetism","Gravity","Friction","Inertia"] },
  { q: "What is the study of plants called?", a: "botany", choices: ["Zoology","Botany","Geology","Biology"] },
  { q: "What is the study of weather called?", a: "meteorology", choices: ["Geology","Meteorology","Astronomy","Ecology"] },
  { q: "What is the study of earthquakes called?", a: "seismology", choices: ["Volcanology","Seismology","Geology","Meteorology"] },
  { q: "Which element is needed for breathing?", a: "oxygen", choices: ["Nitrogen","Oxygen","Hydrogen","Helium"] },

  // ===== History (50) =====
  { q: "Who was the first President of the USA?", a: "george washington", choices: ["Thomas Jefferson","George Washington","Abraham Lincoln","John Adams"] },
  { q: "In what year did WWII end?", a: "1945", choices: ["1942","1945","1948","1939"] },
  { q: "In what year did WWI begin?", a: "1914", choices: ["1912","1914","1916","1918"] },
  { q: "Who painted the Mona Lisa?", a: "da vinci", choices: ["Michelangelo","Van Gogh","Da Vinci","Picasso"] },
  { q: "Who painted the Sistine Chapel ceiling?", a: "michelangelo", choices: ["Raphael","Michelangelo","Da Vinci","Donatello"] },
  { q: "Who was the first man on the Moon?", a: "neil armstrong", choices: ["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","John Glenn"] },
  { q: "Who was the first woman to fly solo across the Atlantic?", a: "amelia earhart", choices: ["Bessie Coleman","Amelia Earhart","Valentina Tereshkova","Sally Ride"] },
  { q: "Who discovered America in 1492?", a: "columbus", choices: ["Magellan","Columbus","Cook","Vespucci"] },
  { q: "Who invented the telephone?", a: "bell", choices: ["Edison","Bell","Tesla","Marconi"] },
  { q: "Who invented the lightbulb?", a: "edison", choices: ["Edison","Tesla","Franklin","Bell"] },
  { q: "Who wrote the Declaration of Independence?", a: "jefferson", choices: ["Washington","Adams","Jefferson","Franklin"] },
  { q: "Which empire built the Colosseum?", a: "roman", choices: ["Greek","Roman","Egyptian","Persian"] },
  { q: "Which civilization built Machu Picchu?", a: "inca", choices: ["Maya","Aztec","Inca","Olmec"] },
  { q: "Which civilization built the pyramids of Giza?", a: "egyptian", choices: ["Greek","Egyptian","Persian","Roman"] },
  { q: "When did the Berlin Wall fall?", a: "1989", choices: ["1985","1987","1989","1991"] },
  { q: "When did the Titanic sink?", a: "1912", choices: ["1905","1912","1918","1923"] },
  { q: "In which year did the Soviet Union dissolve?", a: "1991", choices: ["1989","1990","1991","1993"] },
  { q: "Who was known as the Iron Lady?", a: "thatcher", choices: ["Merkel","Thatcher","May","Clinton"] },
  { q: "Who wrote 'I Have a Dream' speech?", a: "martin luther king jr.", choices: ["Malcolm X","Martin Luther King Jr.","Barack Obama","Frederick Douglass"] },
  { q: "Who was the first emperor of China?", a: "qin shi huang", choices: ["Kangxi","Qin Shi Huang","Han Wu","Tang Taizong"] },
  { q: "Who was the British PM during most of WWII?", a: "churchill", choices: ["Chamberlain","Churchill","Attlee","Eden"] },
  { q: "What year did the French Revolution begin?", a: "1789", choices: ["1776","1789","1799","1815"] },
  { q: "Who was Napoleon's final defeat at?", a: "waterloo", choices: ["Trafalgar","Borodino","Waterloo","Austerlitz"] },
  { q: "Which queen had the longest reign in UK history?", a: "elizabeth ii", choices: ["Victoria","Elizabeth II","Elizabeth I","Mary I"] },
  { q: "Who painted 'Starry Night'?", a: "van gogh", choices: ["Monet","Van Gogh","Cezanne","Renoir"] },
  { q: "Which ancient wonder was in Alexandria?", a: "lighthouse", choices: ["Pyramid","Lighthouse","Colossus","Gardens"] },
  { q: "Who led India to independence?", a: "gandhi", choices: ["Nehru","Gandhi","Bose","Patel"] },
  { q: "Who was the first female PM of the UK?", a: "thatcher", choices: ["May","Thatcher","Truss","Cameron"] },
  { q: "What year did the Cold War end?", a: "1991", choices: ["1989","1991","1995","1985"] },
  { q: "Which US president ended slavery?", a: "lincoln", choices: ["Washington","Lincoln","Jefferson","Grant"] },
  { q: "What did the Wright Brothers invent?", a: "airplane", choices: ["Car","Airplane","Telephone","Radio"] },
  { q: "Which ship explored on the voyage of Charles Darwin?", a: "hms beagle", choices: ["HMS Endeavour","HMS Beagle","HMS Victory","HMS Bounty"] },
  { q: "Who wrote 'The Communist Manifesto'?", a: "marx", choices: ["Lenin","Marx","Stalin","Engels"] },
  { q: "In which year did India gain independence?", a: "1947", choices: ["1945","1947","1950","1942"] },
  { q: "Which country was first to give women the vote?", a: "new zealand", choices: ["USA","UK","New Zealand","Australia"] },
  { q: "Who was the longest-serving US president?", a: "franklin d. roosevelt", choices: ["Lincoln","Franklin D. Roosevelt","Reagan","Obama"] },
  { q: "Who founded Microsoft?", a: "bill gates", choices: ["Steve Jobs","Bill Gates","Larry Page","Mark Zuckerberg"] },
  { q: "Who founded Apple?", a: "steve jobs", choices: ["Bill Gates","Steve Jobs","Elon Musk","Tim Cook"] },
  { q: "Who founded Facebook?", a: "zuckerberg", choices: ["Jobs","Musk","Zuckerberg","Bezos"] },
  { q: "Who founded Amazon?", a: "bezos", choices: ["Musk","Bezos","Gates","Jobs"] },
  { q: "Who founded SpaceX?", a: "musk", choices: ["Bezos","Musk","Branson","Page"] },
  { q: "Which ship sank in 1912?", a: "titanic", choices: ["Lusitania","Titanic","Britannic","Olympic"] },
  { q: "What was the name of the first artificial satellite?", a: "sputnik", choices: ["Vostok","Sputnik","Apollo","Voyager"] },
  { q: "Who painted 'The Persistence of Memory'?", a: "dali", choices: ["Picasso","Dali","Magritte","Miro"] },
  { q: "Which empire was ruled by Genghis Khan?", a: "mongol", choices: ["Ottoman","Mongol","Persian","Roman"] },
  { q: "What year did the USA declare independence?", a: "1776", choices: ["1763","1776","1789","1812"] },
  { q: "Who assassinated Abraham Lincoln?", a: "john wilkes booth", choices: ["Lee Harvey Oswald","John Wilkes Booth","Charles Guiteau","Leon Czolgosz"] },
  { q: "Where did the D-Day landings take place?", a: "normandy", choices: ["Sicily","Normandy","Brittany","Dunkirk"] },
  { q: "Who was the first Tudor king of England?", a: "henry vii", choices: ["Henry VII","Henry VIII","Edward VI","Richard III"] },
  { q: "What was the capital of the Byzantine Empire?", a: "constantinople", choices: ["Rome","Constantinople","Athens","Antioch"] },

  // ===== Literature & Language (40) =====
  { q: "Who wrote 'Hamlet'?", a: "shakespeare", choices: ["Dickens","Shakespeare","Tolkien","Wilde"] },
  { q: "Who wrote 'Romeo and Juliet'?", a: "shakespeare", choices: ["Shakespeare","Marlowe","Chaucer","Milton"] },
  { q: "Who wrote 'Pride and Prejudice'?", a: "jane austen", choices: ["Bronte","Jane Austen","Eliot","Woolf"] },
  { q: "Who wrote '1984'?", a: "orwell", choices: ["Huxley","Orwell","Bradbury","Asimov"] },
  { q: "Who wrote 'Brave New World'?", a: "huxley", choices: ["Orwell","Huxley","Burgess","Atwood"] },
  { q: "Who wrote 'The Great Gatsby'?", a: "fitzgerald", choices: ["Hemingway","Fitzgerald","Steinbeck","Faulkner"] },
  { q: "Who wrote 'War and Peace'?", a: "tolstoy", choices: ["Dostoevsky","Tolstoy","Chekhov","Pushkin"] },
  { q: "Who wrote 'Crime and Punishment'?", a: "dostoevsky", choices: ["Tolstoy","Dostoevsky","Gogol","Turgenev"] },
  { q: "Who wrote 'The Lord of the Rings'?", a: "tolkien", choices: ["Lewis","Tolkien","Rowling","Pullman"] },
  { q: "Who wrote 'Harry Potter'?", a: "rowling", choices: ["Tolkien","Rowling","Lewis","Pratchett"] },
  { q: "Who wrote 'A Song of Ice and Fire'?", a: "george r.r. martin", choices: ["Brandon Sanderson","George R.R. Martin","Robert Jordan","Patrick Rothfuss"] },
  { q: "Who wrote 'Moby-Dick'?", a: "melville", choices: ["Hawthorne","Melville","Twain","Poe"] },
  { q: "Who wrote 'The Catcher in the Rye'?", a: "salinger", choices: ["Vonnegut","Salinger","Kerouac","Bukowski"] },
  { q: "Who wrote 'To Kill a Mockingbird'?", a: "harper lee", choices: ["Truman Capote","Harper Lee","Toni Morrison","Maya Angelou"] },
  { q: "Who wrote 'The Odyssey'?", a: "homer", choices: ["Virgil","Homer","Sophocles","Plato"] },
  { q: "Who wrote 'Don Quixote'?", a: "cervantes", choices: ["Lorca","Cervantes","Borges","Marquez"] },
  { q: "Who wrote 'The Divine Comedy'?", a: "dante", choices: ["Petrarch","Dante","Boccaccio","Machiavelli"] },
  { q: "Who wrote 'Faust'?", a: "goethe", choices: ["Schiller","Goethe","Kant","Hesse"] },
  { q: "Who wrote 'Les Misérables'?", a: "victor hugo", choices: ["Dumas","Victor Hugo","Balzac","Zola"] },
  { q: "Who wrote 'The Picture of Dorian Gray'?", a: "wilde", choices: ["Doyle","Wilde","Stoker","Stevenson"] },
  { q: "Who wrote 'Dracula'?", a: "stoker", choices: ["Shelley","Stoker","Poe","Lovecraft"] },
  { q: "Who wrote 'Frankenstein'?", a: "shelley", choices: ["Shelley","Stoker","Wells","Byron"] },
  { q: "Who created Sherlock Holmes?", a: "doyle", choices: ["Christie","Doyle","Chesterton","Sayers"] },
  { q: "Who wrote 'Murder on the Orient Express'?", a: "agatha christie", choices: ["Agatha Christie","Doyle","Conan","Sayers"] },
  { q: "Who wrote 'Animal Farm'?", a: "orwell", choices: ["Huxley","Orwell","Lewis","Wells"] },
  { q: "Who wrote 'The Old Man and the Sea'?", a: "hemingway", choices: ["Steinbeck","Hemingway","Fitzgerald","Faulkner"] },
  { q: "How many plays did Shakespeare write (approx)?", a: "39", choices: ["20","30","39","50"] },
  { q: "What is the longest novel in the English language often cited?", a: "in search of lost time", choices: ["War and Peace","Ulysses","In Search of Lost Time","Atlas Shrugged"] },
  { q: "What language has the most native speakers?", a: "mandarin", choices: ["English","Mandarin","Spanish","Hindi"] },
  { q: "How many letters are in the English alphabet?", a: "26", choices: ["24","25","26","27"] },
  { q: "Which language has the most words (commonly cited)?", a: "english", choices: ["Spanish","English","Chinese","French"] },
  { q: "What does 'et cetera' mean?", a: "and so on", choices: ["the same","and so on","for example","that is"] },
  { q: "What does 'i.e.' stand for?", a: "id est", choices: ["id est","exempli gratia","et alii","in extremis"] },
  { q: "What does 'e.g.' stand for?", a: "exempli gratia", choices: ["id est","exempli gratia","et alii","ex gratia"] },
  { q: "What punctuation ends a question?", a: "question mark", choices: ["Period","Question mark","Exclamation","Comma"] },
  { q: "What is a haiku?", a: "japanese poem", choices: ["Greek play","Japanese poem","Italian song","Latin essay"] },
  { q: "Who wrote 'The Tale of Genji'?", a: "murasaki shikibu", choices: ["Basho","Murasaki Shikibu","Soseki","Kawabata"] },
  { q: "What is the plural of 'octopus' (common)?", a: "octopuses", choices: ["Octopi","Octopuses","Octopodes","Octops"] },
  { q: "What is the longest English word commonly cited?", a: "pneumonoultramicroscopicsilicovolcanoconiosis", choices: ["Antidisestablishmentarianism","Pneumonoultramicroscopicsilicovolcanoconiosis","Floccinaucinihilipilification","Hippopotomonstrosesquippedaliophobia"] },
  { q: "Who wrote 'The Hobbit'?", a: "tolkien", choices: ["Lewis","Tolkien","Pullman","Rowling"] },

  // ===== Math (30) =====
  { q: "What is 7 x 8?", a: "56", choices: ["54","56","64","48"] },
  { q: "What is 12 x 12?", a: "144", choices: ["124","134","144","156"] },
  { q: "What is 15 x 15?", a: "225", choices: ["205","215","225","235"] },
  { q: "What is the square root of 144?", a: "12", choices: ["10","11","12","13"] },
  { q: "What is the square root of 225?", a: "15", choices: ["14","15","16","17"] },
  { q: "What is pi to 2 decimal places?", a: "3.14", choices: ["3.12","3.14","3.16","3.18"] },
  { q: "How many sides does a hexagon have?", a: "6", choices: ["5","6","7","8"] },
  { q: "How many sides does a pentagon have?", a: "5", choices: ["4","5","6","7"] },
  { q: "How many sides does an octagon have?", a: "8", choices: ["6","7","8","9"] },
  { q: "How many degrees in a circle?", a: "360", choices: ["180","270","360","720"] },
  { q: "How many degrees in a right angle?", a: "90", choices: ["45","90","180","360"] },
  { q: "How many degrees in a triangle's interior angles?", a: "180", choices: ["90","180","270","360"] },
  { q: "What is 25% of 200?", a: "50", choices: ["25","50","75","100"] },
  { q: "What is 10% of 1000?", a: "100", choices: ["50","100","150","200"] },
  { q: "What is 2 to the power of 10?", a: "1024", choices: ["512","1024","2048","4096"] },
  { q: "What is the largest prime less than 20?", a: "19", choices: ["17","18","19","23"] },
  { q: "Is 91 a prime number?", a: "no", choices: ["Yes","No","Maybe","Only sometimes"] },
  { q: "What is 0! (zero factorial)?", a: "1", choices: ["0","1","Undefined","Infinity"] },
  { q: "Who is known as the father of geometry?", a: "euclid", choices: ["Pythagoras","Euclid","Archimedes","Newton"] },
  { q: "What is the Fibonacci number after 13?", a: "21", choices: ["18","19","20","21"] },
  { q: "How many minutes in a day?", a: "1440", choices: ["720","1440","2880","60"] },
  { q: "How many seconds in an hour?", a: "3600", choices: ["360","600","3600","60"] },
  { q: "What is 999 + 1?", a: "1000", choices: ["999","1000","1001","1100"] },
  { q: "What is half of 200?", a: "100", choices: ["50","100","150","75"] },
  { q: "What is one-third of 90?", a: "30", choices: ["20","30","45","60"] },
  { q: "What number is represented by Roman numeral 'L'?", a: "50", choices: ["5","50","500","100"] },
  { q: "What number is represented by Roman numeral 'M'?", a: "1000", choices: ["100","500","1000","10000"] },
  { q: "What is the next prime after 7?", a: "11", choices: ["9","10","11","13"] },
  { q: "How many zeros are in a million?", a: "6", choices: ["5","6","7","9"] },
  { q: "How many zeros are in a billion (short scale)?", a: "9", choices: ["6","9","12","15"] },

  // ===== Sports (40) =====
  { q: "How many players are on a soccer team on the field?", a: "11", choices: ["9","10","11","12"] },
  { q: "How many players are on a basketball team on the court?", a: "5", choices: ["4","5","6","7"] },
  { q: "How many players are on a baseball team on the field?", a: "9", choices: ["7","8","9","10"] },
  { q: "How many players are on a cricket team?", a: "11", choices: ["9","10","11","12"] },
  { q: "How many players on a volleyball team on the court?", a: "6", choices: ["5","6","7","8"] },
  { q: "How often are the Summer Olympics held?", a: "4 years", choices: ["2 years","3 years","4 years","5 years"] },
  { q: "Where were the 2020 Summer Olympics held?", a: "tokyo", choices: ["Rio","Tokyo","Paris","London"] },
  { q: "Where were the 2024 Summer Olympics held?", a: "paris", choices: ["Tokyo","Paris","Los Angeles","Beijing"] },
  { q: "How many rings on the Olympic flag?", a: "5", choices: ["4","5","6","7"] },
  { q: "Which country has won the most FIFA World Cups?", a: "brazil", choices: ["Germany","Italy","Brazil","Argentina"] },
  { q: "Who won the 2022 FIFA World Cup?", a: "argentina", choices: ["France","Brazil","Argentina","Germany"] },
  { q: "Who is known as 'The GOAT' of basketball (often)?", a: "michael jordan", choices: ["LeBron James","Michael Jordan","Kobe Bryant","Magic Johnson"] },
  { q: "Who scored the 'Hand of God' goal?", a: "maradona", choices: ["Pele","Maradona","Messi","Ronaldo"] },
  { q: "What sport is Wimbledon associated with?", a: "tennis", choices: ["Cricket","Tennis","Golf","Rugby"] },
  { q: "What sport is the Tour de France?", a: "cycling", choices: ["Running","Cycling","Swimming","Skiing"] },
  { q: "How many holes in a standard round of golf?", a: "18", choices: ["9","18","27","36"] },
  { q: "In tennis, what is a score of zero called?", a: "love", choices: ["Zero","Nil","Love","Duck"] },
  { q: "What is the diameter of a basketball hoop (inches)?", a: "18", choices: ["16","18","20","24"] },
  { q: "How long is an Olympic swimming pool?", a: "50 meters", choices: ["25 meters","50 meters","75 meters","100 meters"] },
  { q: "How many minutes in a soccer match (regular)?", a: "90", choices: ["60","80","90","120"] },
  { q: "How many points is a touchdown worth in American football?", a: "6", choices: ["3","6","7","9"] },
  { q: "What does NBA stand for?", a: "national basketball association", choices: ["National Baseball Association","National Basketball Association","Northern Basketball Alliance","New Basketball Association"] },
  { q: "What does NFL stand for?", a: "national football league", choices: ["National Football League","Northern Football League","New Football League","National Field League"] },
  { q: "What does NHL stand for?", a: "national hockey league", choices: ["National Hockey League","Northern Hockey League","New Hockey League","National Hoops League"] },
  { q: "What color is the bullseye in archery?", a: "yellow", choices: ["Red","Yellow","Blue","Black"] },
  { q: "Which boxer was known as 'The Greatest'?", a: "muhammad ali", choices: ["Mike Tyson","Muhammad Ali","Floyd Mayweather","Joe Frazier"] },
  { q: "What is the national sport of Japan?", a: "sumo", choices: ["Baseball","Sumo","Judo","Karate"] },
  { q: "Which country invented table tennis?", a: "england", choices: ["China","Japan","England","USA"] },
  { q: "Which country invented basketball?", a: "usa", choices: ["USA","Canada","UK","Australia"] },
  { q: "Which country invented cricket?", a: "england", choices: ["India","Australia","England","South Africa"] },
  { q: "Which Formula 1 driver has the most championships (tied)?", a: "hamilton", choices: ["Schumacher","Hamilton","Senna","Vettel"] },
  { q: "Who has the most Grand Slam tennis titles (men's, as of mid-2020s)?", a: "djokovic", choices: ["Federer","Nadal","Djokovic","Murray"] },
  { q: "What sport uses a shuttlecock?", a: "badminton", choices: ["Tennis","Badminton","Squash","Pickleball"] },
  { q: "What is a perfect score in 10-pin bowling?", a: "300", choices: ["200","250","300","500"] },
  { q: "How long is a marathon (km)?", a: "42.195", choices: ["40","41.5","42.195","43"] },
  { q: "In chess, which piece can only move diagonally?", a: "bishop", choices: ["Knight","Bishop","Rook","Queen"] },
  { q: "How many squares on a chessboard?", a: "64", choices: ["32","48","64","100"] },
  { q: "What's the name of the trophy in the NHL?", a: "stanley cup", choices: ["World Cup","Stanley Cup","Lombardi Trophy","Larry O'Brien"] },
  { q: "What sport is Lionel Messi famous for?", a: "soccer", choices: ["Basketball","Soccer","Tennis","Cricket"] },
  { q: "What sport is Tiger Woods famous for?", a: "golf", choices: ["Golf","Tennis","Soccer","Cricket"] },

  // ===== Movies & TV (50) =====
  { q: "Who directed 'Jurassic Park'?", a: "spielberg", choices: ["Lucas","Spielberg","Cameron","Nolan"] },
  { q: "Who directed 'Titanic'?", a: "cameron", choices: ["Cameron","Spielberg","Tarantino","Nolan"] },
  { q: "Who directed 'Inception'?", a: "nolan", choices: ["Cameron","Nolan","Villeneuve","Fincher"] },
  { q: "Who directed 'The Godfather'?", a: "coppola", choices: ["Scorsese","Coppola","Kubrick","Spielberg"] },
  { q: "Who directed 'Pulp Fiction'?", a: "tarantino", choices: ["Tarantino","Rodriguez","Scorsese","Nolan"] },
  { q: "What year was the first Star Wars film released?", a: "1977", choices: ["1975","1977","1980","1983"] },
  { q: "Who played Iron Man in the MCU?", a: "robert downey jr.", choices: ["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"] },
  { q: "Who played Captain America in the MCU?", a: "chris evans", choices: ["Chris Evans","Chris Hemsworth","Chris Pratt","Chris Pine"] },
  { q: "Who played Thor in the MCU?", a: "chris hemsworth", choices: ["Chris Evans","Chris Hemsworth","Chris Pratt","Chris Pine"] },
  { q: "Who played Harry Potter in the films?", a: "daniel radcliffe", choices: ["Daniel Radcliffe","Rupert Grint","Tom Felton","Robert Pattinson"] },
  { q: "Who played Hermione Granger?", a: "emma watson", choices: ["Emma Watson","Emma Stone","Emma Roberts","Emma Thompson"] },
  { q: "Who played Frodo in 'The Lord of the Rings'?", a: "elijah wood", choices: ["Elijah Wood","Tobey Maguire","Sean Astin","Orlando Bloom"] },
  { q: "Who played Jack in 'Titanic'?", a: "leonardo dicaprio", choices: ["Brad Pitt","Leonardo DiCaprio","Matt Damon","Tom Cruise"] },
  { q: "Who played Rose in 'Titanic'?", a: "kate winslet", choices: ["Kate Hudson","Kate Winslet","Kate Beckinsale","Kate Bosworth"] },
  { q: "What is the highest-grossing film as of 2024?", a: "avatar", choices: ["Avengers: Endgame","Avatar","Titanic","Star Wars: TFA"] },
  { q: "Which animated film features Simba?", a: "the lion king", choices: ["The Lion King","Madagascar","Tarzan","Bambi"] },
  { q: "Which animated film features Woody and Buzz?", a: "toy story", choices: ["Cars","Toy Story","Up","Finding Nemo"] },
  { q: "Which animated film features Elsa?", a: "frozen", choices: ["Frozen","Tangled","Moana","Brave"] },
  { q: "What is the name of the boy in 'Stranger Things' with telekinetic powers?", a: "eleven", choices: ["Mike","Will","Eleven","Dustin"] },
  { q: "What is the name of the cafe in 'Friends'?", a: "central perk", choices: ["Central Park","Central Perk","Cafe Nervosa","Luke's"] },
  { q: "Who plays Sheldon in 'The Big Bang Theory'?", a: "jim parsons", choices: ["Jim Parsons","Johnny Galecki","Simon Helberg","Kunal Nayyar"] },
  { q: "What show features the Iron Throne?", a: "game of thrones", choices: ["The Witcher","Game of Thrones","Vikings","Rome"] },
  { q: "Who created 'Breaking Bad'?", a: "vince gilligan", choices: ["David Chase","Vince Gilligan","David Simon","Aaron Sorkin"] },
  { q: "Who plays Walter White?", a: "bryan cranston", choices: ["Aaron Paul","Bryan Cranston","Bob Odenkirk","Jonathan Banks"] },
  { q: "What is the name of the family in 'The Simpsons'?", a: "simpson", choices: ["Simpson","Griffin","Smith","Belcher"] },
  { q: "What is the name of the family in 'Family Guy'?", a: "griffin", choices: ["Simpson","Griffin","Smith","Belcher"] },
  { q: "What is the name of the family in 'Bob's Burgers'?", a: "belcher", choices: ["Simpson","Griffin","Smith","Belcher"] },
  { q: "Who plays James Bond in 'Casino Royale' (2006)?", a: "daniel craig", choices: ["Pierce Brosnan","Daniel Craig","Sean Connery","Roger Moore"] },
  { q: "Which film features Vincent Vega and Jules Winnfield?", a: "pulp fiction", choices: ["Reservoir Dogs","Pulp Fiction","Kill Bill","Sin City"] },
  { q: "Which film features Andy Dufresne?", a: "the shawshank redemption", choices: ["The Green Mile","The Shawshank Redemption","Cast Away","Forrest Gump"] },
  { q: "Who directed 'Schindler's List'?", a: "spielberg", choices: ["Scorsese","Spielberg","Lumet","Kubrick"] },
  { q: "Who directed '2001: A Space Odyssey'?", a: "kubrick", choices: ["Spielberg","Kubrick","Hitchcock","Welles"] },
  { q: "Who directed 'The Dark Knight'?", a: "nolan", choices: ["Burton","Nolan","Snyder","Reeves"] },
  { q: "Who composed the 'Star Wars' theme?", a: "john williams", choices: ["Hans Zimmer","John Williams","Danny Elfman","Howard Shore"] },
  { q: "Who composed the 'Lord of the Rings' score?", a: "howard shore", choices: ["John Williams","Hans Zimmer","Howard Shore","James Horner"] },
  { q: "What anime features ninjas Naruto and Sasuke?", a: "naruto", choices: ["Bleach","Naruto","One Piece","Dragon Ball"] },
  { q: "What anime features pirates and a stretchy hero?", a: "one piece", choices: ["Bleach","Naruto","One Piece","Fairy Tail"] },
  { q: "What anime features Goku?", a: "dragon ball", choices: ["Naruto","Dragon Ball","Bleach","One Punch Man"] },
  { q: "Who directed 'Spirited Away'?", a: "miyazaki", choices: ["Shinkai","Miyazaki","Takahata","Hosoda"] },
  { q: "What 1999 film has the line 'I see dead people'?", a: "the sixth sense", choices: ["The Others","The Sixth Sense","The Ring","Sleepy Hollow"] },
  { q: "Who voiced Buzz Lightyear in Toy Story?", a: "tim allen", choices: ["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"] },
  { q: "Who voiced Woody in Toy Story?", a: "tom hanks", choices: ["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"] },
  { q: "Which Marvel movie introduces Black Panther?", a: "captain america: civil war", choices: ["Black Panther","Captain America: Civil War","Avengers","Iron Man 2"] },
  { q: "What is the highest-rated TV show on IMDb (often)?", a: "breaking bad", choices: ["The Wire","Breaking Bad","Game of Thrones","The Sopranos"] },
  { q: "What is the longest-running animated TV series?", a: "the simpsons", choices: ["South Park","The Simpsons","Family Guy","SpongeBob"] },
  { q: "What movie franchise features Ethan Hunt?", a: "mission: impossible", choices: ["James Bond","Mission: Impossible","Bourne","Jack Ryan"] },
  { q: "Which film won Best Picture in 2020?", a: "parasite", choices: ["1917","Parasite","Joker","Once Upon a Time in Hollywood"] },
  { q: "Which film won Best Picture in 2023?", a: "everything everywhere all at once", choices: ["Top Gun: Maverick","Everything Everywhere All at Once","Avatar 2","The Banshees of Inisherin"] },
  { q: "What is the longest film in the MCU 'Infinity Saga' (often cited)?", a: "avengers: endgame", choices: ["Avengers: Infinity War","Avengers: Endgame","Iron Man 3","Black Panther"] },
  { q: "Who plays Wolverine?", a: "hugh jackman", choices: ["Hugh Jackman","Ryan Reynolds","Chris Hemsworth","Tom Hardy"] },

  // ===== Music (40) =====
  { q: "Who sang 'Like a Rolling Stone'?", a: "bob dylan", choices: ["The Beatles","Bob Dylan","Elvis","Johnny Cash"] },
  { q: "Who was known as the King of Pop?", a: "michael jackson", choices: ["Elvis","Michael Jackson","Prince","Justin Timberlake"] },
  { q: "Who was known as the King of Rock and Roll?", a: "elvis presley", choices: ["Chuck Berry","Elvis Presley","Little Richard","Buddy Holly"] },
  { q: "Who sang 'Bohemian Rhapsody'?", a: "queen", choices: ["The Who","Queen","Led Zeppelin","Pink Floyd"] },
  { q: "Who sang 'Imagine'?", a: "john lennon", choices: ["Paul McCartney","John Lennon","George Harrison","Ringo Starr"] },
  { q: "Who sang 'Shape of You'?", a: "ed sheeran", choices: ["Ed Sheeran","Justin Bieber","Bruno Mars","Sam Smith"] },
  { q: "Who sang 'Bad Guy'?", a: "billie eilish", choices: ["Ariana Grande","Billie Eilish","Dua Lipa","Olivia Rodrigo"] },
  { q: "Who is the lead singer of Coldplay?", a: "chris martin", choices: ["Chris Martin","Bono","Mick Jagger","Adam Levine"] },
  { q: "Who is the lead singer of U2?", a: "bono", choices: ["Bono","Sting","Bryan Adams","Phil Collins"] },
  { q: "How many members are in BTS?", a: "7", choices: ["5","6","7","8"] },
  { q: "Which Beatle was murdered in 1980?", a: "john lennon", choices: ["John Lennon","Paul McCartney","George Harrison","Ringo Starr"] },
  { q: "Who composed 'The Four Seasons'?", a: "vivaldi", choices: ["Mozart","Bach","Vivaldi","Beethoven"] },
  { q: "Who composed the 'Moonlight Sonata'?", a: "beethoven", choices: ["Mozart","Bach","Vivaldi","Beethoven"] },
  { q: "How many strings does a standard guitar have?", a: "6", choices: ["4","5","6","7"] },
  { q: "How many strings on a violin?", a: "4", choices: ["3","4","5","6"] },
  { q: "How many keys on a standard piano?", a: "88", choices: ["66","76","88","100"] },
  { q: "What instrument did Louis Armstrong play?", a: "trumpet", choices: ["Saxophone","Trumpet","Trombone","Clarinet"] },
  { q: "What instrument did Jimi Hendrix play?", a: "guitar", choices: ["Bass","Guitar","Drums","Piano"] },
  { q: "Which band sang 'Hotel California'?", a: "eagles", choices: ["Eagles","Doors","Aerosmith","Rolling Stones"] },
  { q: "Which band sang 'Stairway to Heaven'?", a: "led zeppelin", choices: ["Led Zeppelin","Pink Floyd","Deep Purple","Black Sabbath"] },
  { q: "Which band sang 'Smells Like Teen Spirit'?", a: "nirvana", choices: ["Soundgarden","Nirvana","Pearl Jam","Alice in Chains"] },
  { q: "Who sang 'Rolling in the Deep'?", a: "adele", choices: ["Adele","Beyonce","Rihanna","Sia"] },
  { q: "What does DJ stand for?", a: "disc jockey", choices: ["Disco Jockey","Disc Jockey","Dance Jockey","Direct Jockey"] },
  { q: "How many notes in a musical scale (major)?", a: "7", choices: ["5","7","8","12"] },
  { q: "What's the highest female singing voice?", a: "soprano", choices: ["Alto","Soprano","Mezzo","Tenor"] },
  { q: "What's the lowest male singing voice?", a: "bass", choices: ["Tenor","Baritone","Bass","Counter-tenor"] },
  { q: "Who released the album 'Thriller'?", a: "michael jackson", choices: ["Prince","Michael Jackson","Lionel Richie","Stevie Wonder"] },
  { q: "Who is 'Slim Shady'?", a: "eminem", choices: ["Dr. Dre","Eminem","Jay-Z","50 Cent"] },
  { q: "What does 'EDM' stand for?", a: "electronic dance music", choices: ["Electric Dance Music","Electronic Dance Music","Easy Dance Music","Electronic Drum Music"] },
  { q: "Which singer is known as 'Queen B'?", a: "beyonce", choices: ["Beyonce","Britney","Madonna","Mariah"] },
  { q: "Who released 'Anti-Hero' in 2022?", a: "taylor swift", choices: ["Taylor Swift","Olivia Rodrigo","Selena Gomez","Ariana Grande"] },
  { q: "What's K-pop?", a: "korean pop", choices: ["Korean Pop","Kenyan Pop","Kazakh Pop","Kannada Pop"] },
  { q: "Who is the lead singer of Maroon 5?", a: "adam levine", choices: ["Adam Levine","Bruno Mars","John Mayer","Justin Timberlake"] },
  { q: "Which band sang 'Wonderwall'?", a: "oasis", choices: ["Blur","Oasis","Radiohead","Coldplay"] },
  { q: "Which artist is known for 'Purple Rain'?", a: "prince", choices: ["David Bowie","Prince","Michael Jackson","Madonna"] },
  { q: "Who sang 'Sweet Child o' Mine'?", a: "guns n' roses", choices: ["Aerosmith","Guns N' Roses","Bon Jovi","Metallica"] },
  { q: "Who sang 'Billie Jean'?", a: "michael jackson", choices: ["Prince","Michael Jackson","Stevie Wonder","Lionel Richie"] },
  { q: "Who sang 'Single Ladies'?", a: "beyonce", choices: ["Beyonce","Rihanna","Jennifer Lopez","Mariah Carey"] },
  { q: "What's the name of Drake's hometown?", a: "toronto", choices: ["Toronto","Montreal","Vancouver","Atlanta"] },
  { q: "Which K-pop group sings 'Dynamite'?", a: "bts", choices: ["BTS","Blackpink","Twice","EXO"] },

  // ===== Tech & Internet (40) =====
  { q: "What does CPU stand for?", a: "central processing unit", choices: ["Central Processing Unit","Computer Processing Unit","Central Program Unit","Core Processing Unit"] },
  { q: "What does GPU stand for?", a: "graphics processing unit", choices: ["General Processing Unit","Graphics Processing Unit","Graphical Program Unit","Graphics Program Unit"] },
  { q: "What does RAM stand for?", a: "random access memory", choices: ["Read Access Memory","Random Access Memory","Run Application Memory","Random Allocation Memory"] },
  { q: "What does HTML stand for?", a: "hypertext markup language", choices: ["HyperText Markup Language","HighText Machine Language","HyperTool Markup Language","HyperText Marking Language"] },
  { q: "What does CSS stand for?", a: "cascading style sheets", choices: ["Cascading Style Sheets","Computer Style Sheets","Creative Style Sheets","Cascading System Sheets"] },
  { q: "What does URL stand for?", a: "uniform resource locator", choices: ["Universal Resource Locator","Uniform Resource Locator","Unified Resource Locator","Universal Reference Link"] },
  { q: "What year was Google founded?", a: "1998", choices: ["1995","1996","1998","2000"] },
  { q: "What year was Facebook founded?", a: "2004", choices: ["2000","2002","2004","2006"] },
  { q: "What year was Twitter founded?", a: "2006", choices: ["2004","2005","2006","2008"] },
  { q: "What year was YouTube founded?", a: "2005", choices: ["2003","2004","2005","2007"] },
  { q: "Who is the CEO of Tesla?", a: "elon musk", choices: ["Mark Zuckerberg","Elon Musk","Jeff Bezos","Tim Cook"] },
  { q: "Who is the CEO of Apple (as of 2024)?", a: "tim cook", choices: ["Steve Jobs","Tim Cook","Sundar Pichai","Satya Nadella"] },
  { q: "Who is the CEO of Microsoft (as of 2024)?", a: "satya nadella", choices: ["Bill Gates","Satya Nadella","Steve Ballmer","Paul Allen"] },
  { q: "Who is the CEO of Google (Alphabet)?", a: "sundar pichai", choices: ["Larry Page","Sergey Brin","Sundar Pichai","Eric Schmidt"] },
  { q: "What is the most popular search engine?", a: "google", choices: ["Bing","Google","Yahoo","DuckDuckGo"] },
  { q: "What does 'AI' stand for?", a: "artificial intelligence", choices: ["Artificial Intelligence","Automated Information","Adaptive Intelligence","Algorithmic Intelligence"] },
  { q: "What programming language uses 'Hello, World!' as a tradition?", a: "all of them", choices: ["Only C","Only Python","Only JavaScript","All of them"] },
  { q: "What was the first iPhone released year?", a: "2007", choices: ["2005","2006","2007","2008"] },
  { q: "What is the name of Apple's voice assistant?", a: "siri", choices: ["Alexa","Siri","Cortana","Bixby"] },
  { q: "What is the name of Amazon's voice assistant?", a: "alexa", choices: ["Alexa","Siri","Cortana","Bixby"] },
  { q: "What is the name of Microsoft's voice assistant?", a: "cortana", choices: ["Alexa","Siri","Cortana","Bixby"] },
  { q: "What is the name of Samsung's voice assistant?", a: "bixby", choices: ["Alexa","Siri","Cortana","Bixby"] },
  { q: "Who founded Twitter?", a: "jack dorsey", choices: ["Mark Zuckerberg","Jack Dorsey","Evan Spiegel","Kevin Systrom"] },
  { q: "Who founded Instagram?", a: "kevin systrom", choices: ["Mark Zuckerberg","Jack Dorsey","Evan Spiegel","Kevin Systrom"] },
  { q: "Who founded Snapchat?", a: "evan spiegel", choices: ["Mark Zuckerberg","Jack Dorsey","Evan Spiegel","Kevin Systrom"] },
  { q: "Which company makes the Galaxy phones?", a: "samsung", choices: ["LG","Samsung","Sony","Huawei"] },
  { q: "Which company makes the Pixel phones?", a: "google", choices: ["Apple","Google","Samsung","Microsoft"] },
  { q: "What does 'WWW' stand for?", a: "world wide web", choices: ["World Wide Web","World Web Wireless","Wide World Web","Web World Wide"] },
  { q: "Who is considered the inventor of the World Wide Web?", a: "tim berners-lee", choices: ["Bill Gates","Tim Berners-Lee","Vint Cerf","Steve Wozniak"] },
  { q: "What does 'PDF' stand for?", a: "portable document format", choices: ["Personal Document Format","Portable Document Format","Printable Document File","Portable Data Format"] },
  { q: "What is Linux?", a: "operating system", choices: ["Operating System","Browser","Programming Language","Search Engine"] },
  { q: "What is the most-used programming language (often cited)?", a: "python", choices: ["JavaScript","Python","Java","C++"] },
  { q: "What year was Bitcoin introduced?", a: "2009", choices: ["2007","2008","2009","2011"] },
  { q: "Who invented Bitcoin (pseudonym)?", a: "satoshi nakamoto", choices: ["Vitalik Buterin","Satoshi Nakamoto","Elon Musk","Hal Finney"] },
  { q: "What does VPN stand for?", a: "virtual private network", choices: ["Virtual Public Network","Virtual Private Network","Vector Private Network","Very Private Network"] },
  { q: "What does SSD stand for?", a: "solid state drive", choices: ["Solid Storage Drive","Solid State Drive","Static State Drive","System Storage Drive"] },
  { q: "What company makes the Surface tablet?", a: "microsoft", choices: ["Apple","Microsoft","Google","Samsung"] },
  { q: "Which company developed ChatGPT?", a: "openai", choices: ["Google","OpenAI","Microsoft","Meta"] },
  { q: "What does 'OS' stand for?", a: "operating system", choices: ["Open Source","Operating System","Online Service","Output System"] },
  { q: "What is the file extension for an Excel spreadsheet?", a: ".xlsx", choices: [".doc",".xlsx",".ppt",".csv"] },

  // ===== Food & Drink (30) =====
  { q: "What country invented pizza?", a: "italy", choices: ["Italy","Greece","Spain","France"] },
  { q: "What country invented sushi?", a: "japan", choices: ["China","Japan","Korea","Thailand"] },
  { q: "What country is the origin of tacos?", a: "mexico", choices: ["Spain","Mexico","Peru","Cuba"] },
  { q: "What is the main ingredient in guacamole?", a: "avocado", choices: ["Tomato","Avocado","Onion","Pepper"] },
  { q: "What is the main ingredient in hummus?", a: "chickpeas", choices: ["Beans","Chickpeas","Lentils","Peas"] },
  { q: "What fruit is famous for keeping the doctor away?", a: "apple", choices: ["Banana","Apple","Orange","Pear"] },
  { q: "What fruit is yellow and curved?", a: "banana", choices: ["Mango","Banana","Lemon","Pineapple"] },
  { q: "Which fruit has its seeds on the outside?", a: "strawberry", choices: ["Strawberry","Raspberry","Kiwi","Pomegranate"] },
  { q: "What is the most consumed beverage in the world after water?", a: "tea", choices: ["Coffee","Tea","Soda","Juice"] },
  { q: "What country is the origin of croissants?", a: "austria", choices: ["France","Austria","Belgium","Italy"] },
  { q: "What is sake?", a: "japanese rice wine", choices: ["Korean liquor","Japanese rice wine","Chinese tea","Vietnamese coffee"] },
  { q: "What is the main ingredient in bread?", a: "flour", choices: ["Sugar","Flour","Salt","Yeast"] },
  { q: "Which country produces the most coffee?", a: "brazil", choices: ["Colombia","Brazil","Ethiopia","Vietnam"] },
  { q: "Which spice is most expensive by weight?", a: "saffron", choices: ["Vanilla","Saffron","Cardamom","Cinnamon"] },
  { q: "What is the national dish of Spain?", a: "paella", choices: ["Tortilla","Paella","Gazpacho","Churros"] },
  { q: "What is tofu made from?", a: "soybeans", choices: ["Rice","Wheat","Soybeans","Chickpeas"] },
  { q: "What is the main ingredient in chocolate?", a: "cocoa", choices: ["Cocoa","Sugar","Milk","Vanilla"] },
  { q: "Where does champagne come from?", a: "france", choices: ["Italy","France","Spain","Germany"] },
  { q: "What is the main ingredient in a margarita?", a: "tequila", choices: ["Vodka","Rum","Tequila","Gin"] },
  { q: "What is sushi traditionally wrapped in?", a: "nori", choices: ["Nori","Wakame","Kombu","Aonori"] },
  { q: "Which cuisine is curry most associated with?", a: "indian", choices: ["Italian","Indian","Mexican","Chinese"] },
  { q: "What is dim sum?", a: "small chinese dishes", choices: ["Indian breads","Small Chinese dishes","Korean stews","Japanese soups"] },
  { q: "What is a cappuccino topped with?", a: "milk foam", choices: ["Whipped cream","Milk foam","Caramel","Chocolate"] },
  { q: "Which fast food chain has the golden arches?", a: "mcdonald's", choices: ["McDonald's","Burger King","Wendy's","KFC"] },
  { q: "Who created KFC?", a: "colonel sanders", choices: ["Ray Kroc","Colonel Sanders","Dave Thomas","Glen Bell"] },
  { q: "What is the main ingredient in pesto?", a: "basil", choices: ["Spinach","Basil","Parsley","Mint"] },
  { q: "Which country is origin of feta cheese?", a: "greece", choices: ["Italy","France","Greece","Turkey"] },
  { q: "Which fruit is known as the king of fruits in SE Asia?", a: "durian", choices: ["Mango","Durian","Rambutan","Mangosteen"] },
  { q: "What grain is used to make traditional risotto?", a: "rice", choices: ["Wheat","Rice","Barley","Oats"] },
  { q: "Which spice gives curry its yellow color?", a: "turmeric", choices: ["Saffron","Turmeric","Cumin","Paprika"] },

  // ===== Animals & Nature (30) =====
  { q: "Which bird cannot fly?", a: "penguin", choices: ["Eagle","Penguin","Sparrow","Owl"] },
  { q: "Which mammal lays eggs?", a: "platypus", choices: ["Bat","Platypus","Sloth","Kangaroo"] },
  { q: "What is a baby kangaroo called?", a: "joey", choices: ["Calf","Joey","Cub","Pup"] },
  { q: "What is a group of lions called?", a: "pride", choices: ["Herd","Pride","Pack","Flock"] },
  { q: "What is a group of wolves called?", a: "pack", choices: ["Herd","Pride","Pack","Flock"] },
  { q: "What is a group of crows called?", a: "murder", choices: ["Flock","Murder","Pack","Swarm"] },
  { q: "What is a group of fish called?", a: "school", choices: ["School","Pack","Pride","Herd"] },
  { q: "Which animal has the longest neck?", a: "giraffe", choices: ["Giraffe","Ostrich","Camel","Llama"] },
  { q: "What's the largest reptile?", a: "saltwater crocodile", choices: ["Komodo Dragon","Saltwater Crocodile","Anaconda","Alligator"] },
  { q: "What's the only continent with no native reptiles?", a: "antarctica", choices: ["Europe","Antarctica","Australia","Arctic"] },
  { q: "Which whale is the largest?", a: "blue whale", choices: ["Sperm","Humpback","Blue","Orca"] },
  { q: "How many hearts does an octopus have?", a: "3", choices: ["1","2","3","4"] },
  { q: "Which animal is known for changing color?", a: "chameleon", choices: ["Chameleon","Frog","Lizard","Snake"] },
  { q: "Which bird is the largest?", a: "ostrich", choices: ["Eagle","Albatross","Ostrich","Condor"] },
  { q: "Which mammal can fly?", a: "bat", choices: ["Squirrel","Bat","Lemur","Sugar glider"] },
  { q: "How long can a camel survive without water (approx)?", a: "1 week", choices: ["1 day","3 days","1 week","1 month"] },
  { q: "Which fish is known for being electric?", a: "electric eel", choices: ["Catfish","Electric Eel","Stingray","Pufferfish"] },
  { q: "What do pandas mainly eat?", a: "bamboo", choices: ["Fish","Bamboo","Berries","Insects"] },
  { q: "What is the tallest tree species?", a: "redwood", choices: ["Oak","Redwood","Pine","Birch"] },
  { q: "What tree do acorns come from?", a: "oak", choices: ["Maple","Oak","Birch","Pine"] },
  { q: "What is the largest flower in the world?", a: "rafflesia", choices: ["Sunflower","Rafflesia","Lotus","Lily"] },
  { q: "Which insect produces silk?", a: "silkworm", choices: ["Spider","Silkworm","Beetle","Ant"] },
  { q: "Which snake is the longest?", a: "reticulated python", choices: ["Anaconda","Reticulated Python","King Cobra","Black Mamba"] },
  { q: "Which animal is the slowest?", a: "sloth", choices: ["Snail","Sloth","Turtle","Koala"] },
  { q: "What's the only mammal that can truly fly?", a: "bat", choices: ["Sugar glider","Bat","Flying squirrel","Lemur"] },
  { q: "What is the smallest bird?", a: "bee hummingbird", choices: ["Sparrow","Bee Hummingbird","Wren","Goldcrest"] },
  { q: "Which animal sleeps the most per day?", a: "koala", choices: ["Sloth","Koala","Lion","Cat"] },
  { q: "What do you call a baby goat?", a: "kid", choices: ["Pup","Kid","Calf","Lamb"] },
  { q: "What do you call a baby swan?", a: "cygnet", choices: ["Chick","Cygnet","Duckling","Joey"] },
  { q: "Which sea creature has 8 arms?", a: "octopus", choices: ["Squid","Octopus","Starfish","Jellyfish"] },

  // ===== Pop Culture & Misc (40) =====
  { q: "What color do you get mixing red and blue?", a: "purple", choices: ["Green","Purple","Orange","Brown"] },
  { q: "What color do you get mixing yellow and blue?", a: "green", choices: ["Purple","Green","Orange","Brown"] },
  { q: "What color do you get mixing red and yellow?", a: "orange", choices: ["Purple","Green","Orange","Brown"] },
  { q: "How many days are in a leap year?", a: "366", choices: ["364","365","366","367"] },
  { q: "How many months have 31 days?", a: "7", choices: ["5","6","7","8"] },
  { q: "Which month has 28 or 29 days?", a: "february", choices: ["January","February","March","April"] },
  { q: "How many hours in a week?", a: "168", choices: ["148","158","168","178"] },
  { q: "What does NASA stand for?", a: "national aeronautics and space administration", choices: ["National Aeronautics and Space Administration","North American Space Agency","National Air and Space Agency","National Aero Science Agency"] },
  { q: "What does FBI stand for?", a: "federal bureau of investigation", choices: ["Federal Bureau of Investigation","Federal Body of Investigation","Federal Bureau of Inquiry","Federal Branch of Investigation"] },
  { q: "What does CIA stand for?", a: "central intelligence agency", choices: ["Central Intelligence Agency","Critical Intelligence Agency","Central Investigation Agency","Country Intelligence Agency"] },
  { q: "What is the largest social network?", a: "facebook", choices: ["Facebook","Twitter","Instagram","TikTok"] },
  { q: "What does 'LOL' stand for?", a: "laugh out loud", choices: ["Lots of Love","Laugh Out Loud","Live On Line","Live Out Loud"] },
  { q: "What does 'BRB' stand for?", a: "be right back", choices: ["Be Right Back","Be Ready Boss","Big Red Bus","Bring Right Back"] },
  { q: "What does 'OMG' stand for?", a: "oh my god", choices: ["Oh My God","Only My Goal","One More Goal","Out My Garden"] },
  { q: "What does 'BTW' stand for?", a: "by the way", choices: ["By the Way","Behind The Wall","Before The Win","Beside The Way"] },
  { q: "What is the color of an emerald?", a: "green", choices: ["Red","Green","Blue","Yellow"] },
  { q: "What is the color of a sapphire?", a: "blue", choices: ["Red","Green","Blue","Yellow"] },
  { q: "What is the color of a ruby?", a: "red", choices: ["Red","Green","Blue","Yellow"] },
  { q: "What metal is liquid at room temperature?", a: "mercury", choices: ["Iron","Mercury","Lead","Tin"] },
  { q: "How many sides does a cube have?", a: "6", choices: ["4","6","8","12"] },
  { q: "How many wheels on a unicycle?", a: "1", choices: ["1","2","3","4"] },
  { q: "What is the tallest building in the world (as of 2024)?", a: "burj khalifa", choices: ["Shanghai Tower","Burj Khalifa","Empire State","Taipei 101"] },
  { q: "What is the largest desert (sand)?", a: "sahara", choices: ["Gobi","Sahara","Kalahari","Arabian"] },
  { q: "Which country invented gunpowder?", a: "china", choices: ["Greece","China","India","Egypt"] },
  { q: "Which country invented paper?", a: "china", choices: ["Greece","China","Egypt","Persia"] },
  { q: "What is the rarest blood type?", a: "ab negative", choices: ["O negative","AB negative","B negative","A negative"] },
  { q: "Who painted the 'Last Supper'?", a: "da vinci", choices: ["Da Vinci","Michelangelo","Caravaggio","Rembrandt"] },
  { q: "Which planet is known as the Morning Star?", a: "venus", choices: ["Mars","Venus","Mercury","Saturn"] },
  { q: "Which planet has a Great Red Spot?", a: "jupiter", choices: ["Mars","Jupiter","Saturn","Uranus"] },
  { q: "Which game is played on a 64-square board?", a: "chess", choices: ["Checkers","Chess","Go","Backgammon"] },
  { q: "Which game uses 'mate' to win?", a: "chess", choices: ["Chess","Checkers","Go","Risk"] },
  { q: "Which card game involves 'Uno' when you have one card?", a: "uno", choices: ["Uno","Skip-Bo","Phase 10","Crazy Eights"] },
  { q: "Which game features colored ghosts named Blinky, Pinky, Inky, Clyde?", a: "pac-man", choices: ["Pac-Man","Donkey Kong","Tetris","Galaga"] },
  { q: "Which game features falling blocks?", a: "tetris", choices: ["Pac-Man","Tetris","Snake","Mario"] },
  { q: "Which video game franchise features Mario?", a: "super mario", choices: ["Sonic","Super Mario","Zelda","Kirby"] },
  { q: "Which video game franchise features Link?", a: "the legend of zelda", choices: ["Final Fantasy","The Legend of Zelda","Metroid","Mario"] },
  { q: "Which video game franchise features Master Chief?", a: "halo", choices: ["Halo","Doom","Call of Duty","Destiny"] },
  { q: "Which video game franchise features Kratos?", a: "god of war", choices: ["Devil May Cry","God of War","Bayonetta","Ninja Gaiden"] },
  { q: "Which video game franchise features Pikachu?", a: "pokemon", choices: ["Digimon","Pokemon","Yo-kai Watch","Bakugan"] },
  { q: "Who is the main character of 'Sonic the Hedgehog'?", a: "sonic", choices: ["Tails","Sonic","Knuckles","Shadow"] },

  // ===== World & Society (40) =====
  { q: "What is the largest religion in the world?", a: "christianity", choices: ["Islam","Christianity","Hinduism","Buddhism"] },
  { q: "Who founded Buddhism?", a: "siddhartha gautama", choices: ["Confucius","Siddhartha Gautama","Lao Tzu","Mahavira"] },
  { q: "What is the holy book of Islam?", a: "quran", choices: ["Bible","Quran","Torah","Vedas"] },
  { q: "What is the holy book of Judaism?", a: "torah", choices: ["Bible","Quran","Torah","Vedas"] },
  { q: "What is the holy book of Hinduism (often cited)?", a: "vedas", choices: ["Bible","Quran","Torah","Vedas"] },
  { q: "What does UN stand for?", a: "united nations", choices: ["United Nations","Universal Nations","United Network","United North"] },
  { q: "What does NATO stand for?", a: "north atlantic treaty organization", choices: ["North Atlantic Treaty Organization","Northern Atlantic Trade Organization","National Atlantic Treaty Org","North American Treaty Org"] },
  { q: "What does EU stand for?", a: "european union", choices: ["European Union","European Unity","Eastern Union","European Universe"] },
  { q: "Where is the UN headquartered?", a: "new york", choices: ["Geneva","New York","Brussels","Vienna"] },
  { q: "Where is the EU headquartered?", a: "brussels", choices: ["Brussels","Strasbourg","Paris","Berlin"] },
  { q: "What is the world's most spoken second language?", a: "english", choices: ["French","Spanish","English","Mandarin"] },
  { q: "What does WHO stand for?", a: "world health organization", choices: ["World Health Organization","World Help Organization","Wide Health Org","World Hospitals Org"] },
  { q: "Which country has the largest economy (GDP)?", a: "usa", choices: ["China","USA","Japan","Germany"] },
  { q: "Which country has the largest population?", a: "india", choices: ["China","India","USA","Indonesia"] },
  { q: "Which country has the most Nobel laureates?", a: "usa", choices: ["UK","USA","Germany","France"] },
  { q: "What does GDP stand for?", a: "gross domestic product", choices: ["Gross Domestic Product","General Domestic Production","Global Direct Profit","Gross Domestic Profit"] },
  { q: "Which currency does Japan use?", a: "yen", choices: ["Won","Yen","Yuan","Rupee"] },
  { q: "Which currency does China use?", a: "yuan", choices: ["Won","Yen","Yuan","Rupee"] },
  { q: "Which currency does South Korea use?", a: "won", choices: ["Won","Yen","Yuan","Rupee"] },
  { q: "Which currency does India use?", a: "rupee", choices: ["Won","Yen","Yuan","Rupee"] },
  { q: "What is the currency of Switzerland?", a: "swiss franc", choices: ["Euro","Swiss Franc","Krone","Pound"] },
  { q: "Which country has the most pyramids?", a: "sudan", choices: ["Egypt","Sudan","Mexico","Peru"] },
  { q: "Which religion celebrates Diwali?", a: "hinduism", choices: ["Islam","Hinduism","Buddhism","Sikhism"] },
  { q: "Which religion celebrates Ramadan?", a: "islam", choices: ["Islam","Hinduism","Christianity","Judaism"] },
  { q: "Which religion celebrates Hanukkah?", a: "judaism", choices: ["Islam","Hinduism","Christianity","Judaism"] },
  { q: "Which country is shaped like a hexagon (approx)?", a: "france", choices: ["Germany","France","Spain","Italy"] },
  { q: "Which country has koalas in the wild?", a: "australia", choices: ["New Zealand","Australia","South Africa","Indonesia"] },
  { q: "Which country has kiwi birds?", a: "new zealand", choices: ["Australia","New Zealand","Fiji","Samoa"] },
  { q: "Which country invented karate?", a: "japan", choices: ["China","Japan","Korea","Thailand"] },
  { q: "Which country invented taekwondo?", a: "south korea", choices: ["China","Japan","South Korea","Vietnam"] },
  { q: "Which country invented kung fu?", a: "china", choices: ["China","Japan","Korea","Vietnam"] },
  { q: "Where did the marathon originate?", a: "greece", choices: ["Italy","Greece","Egypt","Rome"] },
  { q: "Where did the Olympic Games originate?", a: "greece", choices: ["Italy","Greece","Egypt","England"] },
  { q: "What is the most widely used measuring system in the world?", a: "metric", choices: ["Imperial","Metric","US Customary","Chinese"] },
  { q: "Which country gifted the Statue of Liberty to the USA?", a: "france", choices: ["UK","France","Germany","Italy"] },
  { q: "What is the largest lake by surface area?", a: "caspian sea", choices: ["Lake Superior","Caspian Sea","Lake Victoria","Lake Baikal"] },
  { q: "What is the deepest lake in the world?", a: "lake baikal", choices: ["Lake Superior","Caspian Sea","Lake Victoria","Lake Baikal"] },
  { q: "Which country is home to the Amazon rainforest's largest portion?", a: "brazil", choices: ["Peru","Brazil","Colombia","Venezuela"] },
  { q: "What animal appears on the Australian coat of arms with a kangaroo?", a: "emu", choices: ["Koala","Emu","Wombat","Dingo"] },
  { q: "What does 'SOS' stand for (commonly cited)?", a: "save our souls", choices: ["Save Our Ship","Save Our Souls","Send Out Soldiers","Sound Of Sirens"] },
];
