/**
 * Internal link pool for auto-publish (same data as automation-scripts/chatroom-urls.json).
 * Inlined so the serverless bundle does not depend on a cwd JSON file.
 */
export const chatroomUrls = {
  interest: [
    "https://yaarzo.com/cricket-chat-room",
    "https://yaarzo.com/football-chat-room",
    "https://yaarzo.com/gaming-chat-room",
    "https://yaarzo.com/music-chat-room",
    "https://yaarzo.com/movies-chat-room",
    "https://yaarzo.com/bollywood-chat-room",
    "https://yaarzo.com/anime-chat-room",
    "https://yaarzo.com/poetry-chat-room",
    "https://yaarzo.com/technology-chat-room",
    "https://yaarzo.com/sports-chat-room",
    "https://yaarzo.com/books-chat-room",
    "https://yaarzo.com/travel-chat-room",
    "https://yaarzo.com/food-chat-room",
    "https://yaarzo.com/study-chat-room",
    "https://yaarzo.com/relationship-chat-room",
  ],
  type: [
    "https://yaarzo.com/girls-chat-room",
    "https://yaarzo.com/boys-chat-room",
    "https://yaarzo.com/friendship-chat-room",
    "https://yaarzo.com/dating-chat-room",
    "https://yaarzo.com/free-chat-room",
    "https://yaarzo.com/online-chat-room",
    "https://yaarzo.com/random-chat-room",
    "https://yaarzo.com/anonymous-chat-room",
    "https://yaarzo.com/chat-with-strangers",
    "https://yaarzo.com/group-chat-room",
    "https://yaarzo.com/social-chat-room",
    "https://yaarzo.com/singles-chat-room",
    "https://yaarzo.com/student-chat-room",
    "https://yaarzo.com/international-chat-room",
  ],
  keywordMap: {
    gaming: "https://yaarzo.com/gaming-chat-room",
    game: "https://yaarzo.com/gaming-chat-room",
    sport: "https://yaarzo.com/sports-chat-room",
    cricket: "https://yaarzo.com/cricket-chat-room",
    football: "https://yaarzo.com/football-chat-room",
    music: "https://yaarzo.com/music-chat-room",
    movie: "https://yaarzo.com/movies-chat-room",
    anime: "https://yaarzo.com/anime-chat-room",
    book: "https://yaarzo.com/books-chat-room",
    travel: "https://yaarzo.com/travel-chat-room",
    student: "https://yaarzo.com/student-chat-room",
    language: "https://yaarzo.com/international-chat-room",
    dating: "https://yaarzo.com/dating-chat-room",
    friend: "https://yaarzo.com/friendship-chat-room",
    stranger: "https://yaarzo.com/chat-with-strangers",
    anonymous: "https://yaarzo.com/anonymous-chat-room",
    community: "https://yaarzo.com/online-chat-room",
  } as Record<string, string>,
};
