/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FindFriendsRouteImport } from './routes/find-friends'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as FeedSlugRouteImport } from './routes/feed.$slug'
import { Route as ApiPublicGuestCleanupRouteImport } from './routes/api/public/guest-cleanup'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FindFriendsRoute = FindFriendsRouteImport.update({
  id: '/find-friends',
  path: '/find-friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugRoute = FeedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeedRoute,
} as any)
const ApiPublicGuestCleanupRoute = ApiPublicGuestCleanupRouteImport.update({
  id: '/api/public/guest-cleanup',
  path: '/api/public/guest-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/feed': typeof FeedRouteWithChildren
  '/find-friends': typeof FindFriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/feed': typeof FeedRouteWithChildren
  '/find-friends': typeof FindFriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/feed': typeof FeedRouteWithChildren
  '/find-friends': typeof FindFriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/achievements'
    | '/feed'
    | '/find-friends'
    | '/leaderboard'
    | '/reset-password'
    | '/feed/$slug'
    | '/u/$username'
    | '/api/public/guest-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/achievements'
    | '/feed'
    | '/find-friends'
    | '/leaderboard'
    | '/reset-password'
    | '/feed/$slug'
    | '/u/$username'
    | '/api/public/guest-cleanup'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/achievements'
    | '/feed'
    | '/find-friends'
    | '/leaderboard'
    | '/reset-password'
    | '/feed/$slug'
    | '/u/$username'
    | '/api/public/guest-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AchievementsRoute: typeof AchievementsRoute
  FeedRoute: typeof FeedRouteWithChildren
  FindFriendsRoute: typeof FindFriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicGuestCleanupRoute: typeof ApiPublicGuestCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-friends': {
      id: '/find-friends'
      path: '/find-friends'
      fullPath: '/find-friends'
      preLoaderRoute: typeof FindFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug': {
      id: '/feed/$slug'
      path: '/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof FeedSlugRouteImport
      parentRoute: typeof FeedRoute
    }
    '/api/public/guest-cleanup': {
      id: '/api/public/guest-cleanup'
      path: '/api/public/guest-cleanup'
      fullPath: '/api/public/guest-cleanup'
      preLoaderRoute: typeof ApiPublicGuestCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FeedRouteChildren {
  FeedSlugRoute: typeof FeedSlugRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedSlugRoute: FeedSlugRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AchievementsRoute: AchievementsRoute,
  FeedRoute: FeedRouteWithChildren,
  FindFriendsRoute: FindFriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicGuestCleanupRoute: ApiPublicGuestCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
