/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiPublicGuestCleanupRouteImport } from './routes/api/public/guest-cleanup'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestCleanupRoute = ApiPublicGuestCleanupRouteImport.update({
  id: '/api/public/guest-cleanup',
  path: '/api/public/guest-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/achievements'
    | '/feed'
    | '/leaderboard'
    | '/u/$username'
    | '/api/public/guest-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/achievements'
    | '/feed'
    | '/leaderboard'
    | '/u/$username'
    | '/api/public/guest-cleanup'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/achievements'
    | '/feed'
    | '/leaderboard'
    | '/u/$username'
    | '/api/public/guest-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AchievementsRoute: typeof AchievementsRoute
  FeedRoute: typeof FeedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicGuestCleanupRoute: typeof ApiPublicGuestCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest-cleanup': {
      id: '/api/public/guest-cleanup'
      path: '/api/public/guest-cleanup'
      fullPath: '/api/public/guest-cleanup'
      preLoaderRoute: typeof ApiPublicGuestCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AchievementsRoute: AchievementsRoute,
  FeedRoute: FeedRoute,
  LeaderboardRoute: LeaderboardRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicGuestCleanupRoute: ApiPublicGuestCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
