/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FindFriendsRouteImport } from './routes/find-friends'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ConfessionsRouteImport } from './routes/confessions'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as FeedSlugRouteImport } from './routes/feed.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUpcomingRouteImport } from './routes/admin.upcoming'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminStaffPermissionsRouteImport } from './routes/admin.staff-permissions'
import { Route as AdminSocialLayoutRouteImport } from './routes/admin.social-layout'
import { Route as AdminSocialFeedRouteImport } from './routes/admin.social-feed'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRetentionRouteImport } from './routes/admin.retention'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRealtimeRouteImport } from './routes/admin.realtime'
import { Route as AdminProgressionRouteImport } from './routes/admin.progression'
import { Route as AdminPollWidgetRouteImport } from './routes/admin.poll-widget'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMediaApisRouteImport } from './routes/admin.media-apis'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminGuestAccessRouteImport } from './routes/admin.guest-access'
import { Route as AdminGeneralRouteImport } from './routes/admin.general'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminFiltersRouteImport } from './routes/admin.filters'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminEconomyRouteImport } from './routes/admin.economy'
import { Route as AdminDjRouteImport } from './routes/admin.dj'
import { Route as AdminConfessionsRouteImport } from './routes/admin.confessions'
import { Route as AdminChatroomsRouteImport } from './routes/admin.chatrooms'
import { Route as AdminBotsRouteImport } from './routes/admin.bots'
import { Route as AdminAutomationRouteImport } from './routes/admin.automation'
import { Route as AdminAuthBackgroundRouteImport } from './routes/admin.auth-background'
import { Route as AdminAppearanceRouteImport } from './routes/admin.appearance'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiChatbotsRouteImport } from './routes/admin.ai-chatbots'
import { Route as AdminAdsScriptsRouteImport } from './routes/admin.ads-scripts'
import { Route as AdminAdPlacementsRouteImport } from './routes/admin.ad-placements'
import { Route as ApiPublicLandingRouteImport } from './routes/api/public/landing'
import { Route as ApiPublicGuestCleanupRouteImport } from './routes/api/public/guest-cleanup'
import { Route as ApiPublicFeedbackShowcaseRouteImport } from './routes/api/public/feedback-showcase'
import { Route as ApiPublicCommunityBgRouteImport } from './routes/api/public/community-bg'
import { Route as AdminUpcomingKeyRouteImport } from './routes/admin.upcoming.$key'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FindFriendsRoute = FindFriendsRouteImport.update({
  id: '/find-friends',
  path: '/find-friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionsRoute = ConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugRoute = FeedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeedRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUpcomingRoute = AdminUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffPermissionsRoute = AdminStaffPermissionsRouteImport.update({
  id: '/staff-permissions',
  path: '/staff-permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialLayoutRoute = AdminSocialLayoutRouteImport.update({
  id: '/social-layout',
  path: '/social-layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialFeedRoute = AdminSocialFeedRouteImport.update({
  id: '/social-feed',
  path: '/social-feed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRetentionRoute = AdminRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRealtimeRoute = AdminRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgressionRoute = AdminProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPollWidgetRoute = AdminPollWidgetRouteImport.update({
  id: '/poll-widget',
  path: '/poll-widget',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaApisRoute = AdminMediaApisRouteImport.update({
  id: '/media-apis',
  path: '/media-apis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestAccessRoute = AdminGuestAccessRouteImport.update({
  id: '/guest-access',
  path: '/guest-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralRoute = AdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiltersRoute = AdminFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEconomyRoute = AdminEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDjRoute = AdminDjRouteImport.update({
  id: '/dj',
  path: '/dj',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfessionsRoute = AdminConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatroomsRoute = AdminChatroomsRouteImport.update({
  id: '/chatrooms',
  path: '/chatrooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotsRoute = AdminBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthBackgroundRoute = AdminAuthBackgroundRouteImport.update({
  id: '/auth-background',
  path: '/auth-background',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiChatbotsRoute = AdminAiChatbotsRouteImport.update({
  id: '/ai-chatbots',
  path: '/ai-chatbots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsScriptsRoute = AdminAdsScriptsRouteImport.update({
  id: '/ads-scripts',
  path: '/ads-scripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdPlacementsRoute = AdminAdPlacementsRouteImport.update({
  id: '/ad-placements',
  path: '/ad-placements',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicLandingRoute = ApiPublicLandingRouteImport.update({
  id: '/api/public/landing',
  path: '/api/public/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestCleanupRoute = ApiPublicGuestCleanupRouteImport.update({
  id: '/api/public/guest-cleanup',
  path: '/api/public/guest-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackShowcaseRoute =
  ApiPublicFeedbackShowcaseRouteImport.update({
    id: '/api/public/feedback-showcase',
    path: '/api/public/feedback-showcase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommunityBgRoute = ApiPublicCommunityBgRouteImport.update({
  id: '/api/public/community-bg',
  path: '/api/public/community-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpcomingKeyRoute = AdminUpcomingKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AdminUpcomingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/banned': typeof BannedRoute
  '/confessions': typeof ConfessionsRoute
  '/feed': typeof FeedRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/find-friends': typeof FindFriendsRoute
  '/games': typeof GamesRoute
  '/groups': typeof GroupsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ad-placements': typeof AdminAdPlacementsRoute
  '/admin/ads-scripts': typeof AdminAdsScriptsRoute
  '/admin/ai-chatbots': typeof AdminAiChatbotsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/auth-background': typeof AdminAuthBackgroundRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/bots': typeof AdminBotsRoute
  '/admin/chatrooms': typeof AdminChatroomsRoute
  '/admin/confessions': typeof AdminConfessionsRoute
  '/admin/dj': typeof AdminDjRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/filters': typeof AdminFiltersRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/guest-access': typeof AdminGuestAccessRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media-apis': typeof AdminMediaApisRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/poll-widget': typeof AdminPollWidgetRoute
  '/admin/progression': typeof AdminProgressionRoute
  '/admin/realtime': typeof AdminRealtimeRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/social-feed': typeof AdminSocialFeedRoute
  '/admin/social-layout': typeof AdminSocialLayoutRoute
  '/admin/staff-permissions': typeof AdminStaffPermissionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/upcoming': typeof AdminUpcomingRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/upcoming/$key': typeof AdminUpcomingKeyRoute
  '/api/public/community-bg': typeof ApiPublicCommunityBgRoute
  '/api/public/feedback-showcase': typeof ApiPublicFeedbackShowcaseRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
  '/api/public/landing': typeof ApiPublicLandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/banned': typeof BannedRoute
  '/confessions': typeof ConfessionsRoute
  '/feed': typeof FeedRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/find-friends': typeof FindFriendsRoute
  '/games': typeof GamesRoute
  '/groups': typeof GroupsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ad-placements': typeof AdminAdPlacementsRoute
  '/admin/ads-scripts': typeof AdminAdsScriptsRoute
  '/admin/ai-chatbots': typeof AdminAiChatbotsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/auth-background': typeof AdminAuthBackgroundRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/bots': typeof AdminBotsRoute
  '/admin/chatrooms': typeof AdminChatroomsRoute
  '/admin/confessions': typeof AdminConfessionsRoute
  '/admin/dj': typeof AdminDjRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/filters': typeof AdminFiltersRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/guest-access': typeof AdminGuestAccessRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media-apis': typeof AdminMediaApisRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/poll-widget': typeof AdminPollWidgetRoute
  '/admin/progression': typeof AdminProgressionRoute
  '/admin/realtime': typeof AdminRealtimeRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/social-feed': typeof AdminSocialFeedRoute
  '/admin/social-layout': typeof AdminSocialLayoutRoute
  '/admin/staff-permissions': typeof AdminStaffPermissionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/upcoming': typeof AdminUpcomingRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/admin/upcoming/$key': typeof AdminUpcomingKeyRoute
  '/api/public/community-bg': typeof ApiPublicCommunityBgRoute
  '/api/public/feedback-showcase': typeof ApiPublicFeedbackShowcaseRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
  '/api/public/landing': typeof ApiPublicLandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account': typeof AccountRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/banned': typeof BannedRoute
  '/confessions': typeof ConfessionsRoute
  '/feed': typeof FeedRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/find-friends': typeof FindFriendsRoute
  '/games': typeof GamesRoute
  '/groups': typeof GroupsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ad-placements': typeof AdminAdPlacementsRoute
  '/admin/ads-scripts': typeof AdminAdsScriptsRoute
  '/admin/ai-chatbots': typeof AdminAiChatbotsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/auth-background': typeof AdminAuthBackgroundRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/bots': typeof AdminBotsRoute
  '/admin/chatrooms': typeof AdminChatroomsRoute
  '/admin/confessions': typeof AdminConfessionsRoute
  '/admin/dj': typeof AdminDjRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/filters': typeof AdminFiltersRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/guest-access': typeof AdminGuestAccessRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media-apis': typeof AdminMediaApisRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/poll-widget': typeof AdminPollWidgetRoute
  '/admin/progression': typeof AdminProgressionRoute
  '/admin/realtime': typeof AdminRealtimeRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/social-feed': typeof AdminSocialFeedRoute
  '/admin/social-layout': typeof AdminSocialLayoutRoute
  '/admin/staff-permissions': typeof AdminStaffPermissionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/upcoming': typeof AdminUpcomingRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/upcoming/$key': typeof AdminUpcomingKeyRoute
  '/api/public/community-bg': typeof ApiPublicCommunityBgRoute
  '/api/public/feedback-showcase': typeof ApiPublicFeedbackShowcaseRoute
  '/api/public/guest-cleanup': typeof ApiPublicGuestCleanupRoute
  '/api/public/landing': typeof ApiPublicLandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/account'
    | '/achievements'
    | '/admin'
    | '/banned'
    | '/confessions'
    | '/feed'
    | '/feedback'
    | '/find-friends'
    | '/games'
    | '/groups'
    | '/leaderboard'
    | '/login'
    | '/pages'
    | '/reels'
    | '/reset-password'
    | '/welcome'
    | '/admin/ad-placements'
    | '/admin/ads-scripts'
    | '/admin/ai-chatbots'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/appearance'
    | '/admin/auth-background'
    | '/admin/automation'
    | '/admin/bots'
    | '/admin/chatrooms'
    | '/admin/confessions'
    | '/admin/dj'
    | '/admin/economy'
    | '/admin/feedback'
    | '/admin/filters'
    | '/admin/games'
    | '/admin/general'
    | '/admin/guest-access'
    | '/admin/homepage'
    | '/admin/media-apis'
    | '/admin/moderation'
    | '/admin/modules'
    | '/admin/pages'
    | '/admin/performance'
    | '/admin/poll-widget'
    | '/admin/progression'
    | '/admin/realtime'
    | '/admin/reports'
    | '/admin/retention'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/social-feed'
    | '/admin/social-layout'
    | '/admin/staff-permissions'
    | '/admin/system'
    | '/admin/upcoming'
    | '/admin/users'
    | '/feed/$slug'
    | '/p/$slug'
    | '/u/$username'
    | '/admin/'
    | '/admin/upcoming/$key'
    | '/api/public/community-bg'
    | '/api/public/feedback-showcase'
    | '/api/public/guest-cleanup'
    | '/api/public/landing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/account'
    | '/achievements'
    | '/banned'
    | '/confessions'
    | '/feed'
    | '/feedback'
    | '/find-friends'
    | '/games'
    | '/groups'
    | '/leaderboard'
    | '/login'
    | '/pages'
    | '/reels'
    | '/reset-password'
    | '/welcome'
    | '/admin/ad-placements'
    | '/admin/ads-scripts'
    | '/admin/ai-chatbots'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/appearance'
    | '/admin/auth-background'
    | '/admin/automation'
    | '/admin/bots'
    | '/admin/chatrooms'
    | '/admin/confessions'
    | '/admin/dj'
    | '/admin/economy'
    | '/admin/feedback'
    | '/admin/filters'
    | '/admin/games'
    | '/admin/general'
    | '/admin/guest-access'
    | '/admin/homepage'
    | '/admin/media-apis'
    | '/admin/moderation'
    | '/admin/modules'
    | '/admin/pages'
    | '/admin/performance'
    | '/admin/poll-widget'
    | '/admin/progression'
    | '/admin/realtime'
    | '/admin/reports'
    | '/admin/retention'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/social-feed'
    | '/admin/social-layout'
    | '/admin/staff-permissions'
    | '/admin/system'
    | '/admin/upcoming'
    | '/admin/users'
    | '/feed/$slug'
    | '/p/$slug'
    | '/u/$username'
    | '/admin'
    | '/admin/upcoming/$key'
    | '/api/public/community-bg'
    | '/api/public/feedback-showcase'
    | '/api/public/guest-cleanup'
    | '/api/public/landing'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/account'
    | '/achievements'
    | '/admin'
    | '/banned'
    | '/confessions'
    | '/feed'
    | '/feedback'
    | '/find-friends'
    | '/games'
    | '/groups'
    | '/leaderboard'
    | '/login'
    | '/pages'
    | '/reels'
    | '/reset-password'
    | '/welcome'
    | '/admin/ad-placements'
    | '/admin/ads-scripts'
    | '/admin/ai-chatbots'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/appearance'
    | '/admin/auth-background'
    | '/admin/automation'
    | '/admin/bots'
    | '/admin/chatrooms'
    | '/admin/confessions'
    | '/admin/dj'
    | '/admin/economy'
    | '/admin/feedback'
    | '/admin/filters'
    | '/admin/games'
    | '/admin/general'
    | '/admin/guest-access'
    | '/admin/homepage'
    | '/admin/media-apis'
    | '/admin/moderation'
    | '/admin/modules'
    | '/admin/pages'
    | '/admin/performance'
    | '/admin/poll-widget'
    | '/admin/progression'
    | '/admin/realtime'
    | '/admin/reports'
    | '/admin/retention'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/social-feed'
    | '/admin/social-layout'
    | '/admin/staff-permissions'
    | '/admin/system'
    | '/admin/upcoming'
    | '/admin/users'
    | '/feed/$slug'
    | '/p/$slug'
    | '/u/$username'
    | '/admin/'
    | '/admin/upcoming/$key'
    | '/api/public/community-bg'
    | '/api/public/feedback-showcase'
    | '/api/public/guest-cleanup'
    | '/api/public/landing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AccountRoute: typeof AccountRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  BannedRoute: typeof BannedRoute
  ConfessionsRoute: typeof ConfessionsRoute
  FeedRoute: typeof FeedRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  FindFriendsRoute: typeof FindFriendsRoute
  GamesRoute: typeof GamesRoute
  GroupsRoute: typeof GroupsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PagesRoute: typeof PagesRoute
  ReelsRoute: typeof ReelsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
  PSlugRoute: typeof PSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicCommunityBgRoute: typeof ApiPublicCommunityBgRoute
  ApiPublicFeedbackShowcaseRoute: typeof ApiPublicFeedbackShowcaseRoute
  ApiPublicGuestCleanupRoute: typeof ApiPublicGuestCleanupRoute
  ApiPublicLandingRoute: typeof ApiPublicLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-friends': {
      id: '/find-friends'
      path: '/find-friends'
      fullPath: '/find-friends'
      preLoaderRoute: typeof FindFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confessions': {
      id: '/confessions'
      path: '/confessions'
      fullPath: '/confessions'
      preLoaderRoute: typeof ConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug': {
      id: '/feed/$slug'
      path: '/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof FeedSlugRouteImport
      parentRoute: typeof FeedRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upcoming': {
      id: '/admin/upcoming'
      path: '/upcoming'
      fullPath: '/admin/upcoming'
      preLoaderRoute: typeof AdminUpcomingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff-permissions': {
      id: '/admin/staff-permissions'
      path: '/staff-permissions'
      fullPath: '/admin/staff-permissions'
      preLoaderRoute: typeof AdminStaffPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-layout': {
      id: '/admin/social-layout'
      path: '/social-layout'
      fullPath: '/admin/social-layout'
      preLoaderRoute: typeof AdminSocialLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-feed': {
      id: '/admin/social-feed'
      path: '/social-feed'
      fullPath: '/admin/social-feed'
      preLoaderRoute: typeof AdminSocialFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retention': {
      id: '/admin/retention'
      path: '/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AdminRetentionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/realtime': {
      id: '/admin/realtime'
      path: '/realtime'
      fullPath: '/admin/realtime'
      preLoaderRoute: typeof AdminRealtimeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/progression': {
      id: '/admin/progression'
      path: '/progression'
      fullPath: '/admin/progression'
      preLoaderRoute: typeof AdminProgressionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/poll-widget': {
      id: '/admin/poll-widget'
      path: '/poll-widget'
      fullPath: '/admin/poll-widget'
      preLoaderRoute: typeof AdminPollWidgetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media-apis': {
      id: '/admin/media-apis'
      path: '/media-apis'
      fullPath: '/admin/media-apis'
      preLoaderRoute: typeof AdminMediaApisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guest-access': {
      id: '/admin/guest-access'
      path: '/guest-access'
      fullPath: '/admin/guest-access'
      preLoaderRoute: typeof AdminGuestAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general': {
      id: '/admin/general'
      path: '/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AdminGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/filters': {
      id: '/admin/filters'
      path: '/filters'
      fullPath: '/admin/filters'
      preLoaderRoute: typeof AdminFiltersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/economy': {
      id: '/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AdminEconomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dj': {
      id: '/admin/dj'
      path: '/dj'
      fullPath: '/admin/dj'
      preLoaderRoute: typeof AdminDjRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/confessions': {
      id: '/admin/confessions'
      path: '/confessions'
      fullPath: '/admin/confessions'
      preLoaderRoute: typeof AdminConfessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatrooms': {
      id: '/admin/chatrooms'
      path: '/chatrooms'
      fullPath: '/admin/chatrooms'
      preLoaderRoute: typeof AdminChatroomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bots': {
      id: '/admin/bots'
      path: '/bots'
      fullPath: '/admin/bots'
      preLoaderRoute: typeof AdminBotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth-background': {
      id: '/admin/auth-background'
      path: '/auth-background'
      fullPath: '/admin/auth-background'
      preLoaderRoute: typeof AdminAuthBackgroundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-chatbots': {
      id: '/admin/ai-chatbots'
      path: '/ai-chatbots'
      fullPath: '/admin/ai-chatbots'
      preLoaderRoute: typeof AdminAiChatbotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads-scripts': {
      id: '/admin/ads-scripts'
      path: '/ads-scripts'
      fullPath: '/admin/ads-scripts'
      preLoaderRoute: typeof AdminAdsScriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-placements': {
      id: '/admin/ad-placements'
      path: '/ad-placements'
      fullPath: '/admin/ad-placements'
      preLoaderRoute: typeof AdminAdPlacementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/landing': {
      id: '/api/public/landing'
      path: '/api/public/landing'
      fullPath: '/api/public/landing'
      preLoaderRoute: typeof ApiPublicLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest-cleanup': {
      id: '/api/public/guest-cleanup'
      path: '/api/public/guest-cleanup'
      fullPath: '/api/public/guest-cleanup'
      preLoaderRoute: typeof ApiPublicGuestCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback-showcase': {
      id: '/api/public/feedback-showcase'
      path: '/api/public/feedback-showcase'
      fullPath: '/api/public/feedback-showcase'
      preLoaderRoute: typeof ApiPublicFeedbackShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/community-bg': {
      id: '/api/public/community-bg'
      path: '/api/public/community-bg'
      fullPath: '/api/public/community-bg'
      preLoaderRoute: typeof ApiPublicCommunityBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upcoming/$key': {
      id: '/admin/upcoming/$key'
      path: '/$key'
      fullPath: '/admin/upcoming/$key'
      preLoaderRoute: typeof AdminUpcomingKeyRouteImport
      parentRoute: typeof AdminUpcomingRoute
    }
  }
}

interface AdminUpcomingRouteChildren {
  AdminUpcomingKeyRoute: typeof AdminUpcomingKeyRoute
}

const AdminUpcomingRouteChildren: AdminUpcomingRouteChildren = {
  AdminUpcomingKeyRoute: AdminUpcomingKeyRoute,
}

const AdminUpcomingRouteWithChildren = AdminUpcomingRoute._addFileChildren(
  AdminUpcomingRouteChildren,
)

interface AdminRouteChildren {
  AdminAdPlacementsRoute: typeof AdminAdPlacementsRoute
  AdminAdsScriptsRoute: typeof AdminAdsScriptsRoute
  AdminAiChatbotsRoute: typeof AdminAiChatbotsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminAuthBackgroundRoute: typeof AdminAuthBackgroundRoute
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminBotsRoute: typeof AdminBotsRoute
  AdminChatroomsRoute: typeof AdminChatroomsRoute
  AdminConfessionsRoute: typeof AdminConfessionsRoute
  AdminDjRoute: typeof AdminDjRoute
  AdminEconomyRoute: typeof AdminEconomyRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFiltersRoute: typeof AdminFiltersRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminGeneralRoute: typeof AdminGeneralRoute
  AdminGuestAccessRoute: typeof AdminGuestAccessRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMediaApisRoute: typeof AdminMediaApisRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminPollWidgetRoute: typeof AdminPollWidgetRoute
  AdminProgressionRoute: typeof AdminProgressionRoute
  AdminRealtimeRoute: typeof AdminRealtimeRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRetentionRoute: typeof AdminRetentionRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSocialFeedRoute: typeof AdminSocialFeedRoute
  AdminSocialLayoutRoute: typeof AdminSocialLayoutRoute
  AdminStaffPermissionsRoute: typeof AdminStaffPermissionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUpcomingRoute: typeof AdminUpcomingRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdPlacementsRoute: AdminAdPlacementsRoute,
  AdminAdsScriptsRoute: AdminAdsScriptsRoute,
  AdminAiChatbotsRoute: AdminAiChatbotsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminAuthBackgroundRoute: AdminAuthBackgroundRoute,
  AdminAutomationRoute: AdminAutomationRoute,
  AdminBotsRoute: AdminBotsRoute,
  AdminChatroomsRoute: AdminChatroomsRoute,
  AdminConfessionsRoute: AdminConfessionsRoute,
  AdminDjRoute: AdminDjRoute,
  AdminEconomyRoute: AdminEconomyRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFiltersRoute: AdminFiltersRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminGeneralRoute: AdminGeneralRoute,
  AdminGuestAccessRoute: AdminGuestAccessRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMediaApisRoute: AdminMediaApisRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminPollWidgetRoute: AdminPollWidgetRoute,
  AdminProgressionRoute: AdminProgressionRoute,
  AdminRealtimeRoute: AdminRealtimeRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRetentionRoute: AdminRetentionRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSocialFeedRoute: AdminSocialFeedRoute,
  AdminSocialLayoutRoute: AdminSocialLayoutRoute,
  AdminStaffPermissionsRoute: AdminStaffPermissionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUpcomingRoute: AdminUpcomingRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FeedRouteChildren {
  FeedSlugRoute: typeof FeedSlugRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedSlugRoute: FeedSlugRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AccountRoute: AccountRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  BannedRoute: BannedRoute,
  ConfessionsRoute: ConfessionsRoute,
  FeedRoute: FeedRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  FindFriendsRoute: FindFriendsRoute,
  GamesRoute: GamesRoute,
  GroupsRoute: GroupsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PagesRoute: PagesRoute,
  ReelsRoute: ReelsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
  PSlugRoute: PSlugRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicCommunityBgRoute: ApiPublicCommunityBgRoute,
  ApiPublicFeedbackShowcaseRoute: ApiPublicFeedbackShowcaseRoute,
  ApiPublicGuestCleanupRoute: ApiPublicGuestCleanupRoute,
  ApiPublicLandingRoute: ApiPublicLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
