-- Phase 3B-1: authoritative platform public channel registry (foundation only).
-- Does NOT modify public.messages, guest chat, presence, typing, or DM/trio policies.

-- ---------------------------------------------------------------------------
-- Permanent channel-number allocator (numbers are never deleted/reused)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.platform_chat_channel_number_alloc (
  channel_number bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Reserve #1 and #2 for system channels; next admin create receives #3+.
INSERT INTO public.platform_chat_channel_number_alloc (channel_number)
OVERRIDING SYSTEM VALUE
VALUES (1), (2)
ON CONFLICT DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.platform_chat_channel_number_alloc', 'channel_number'),
  GREATEST((SELECT COALESCE(MAX(channel_number), 2) FROM public.platform_chat_channel_number_alloc), 2),
  true
);

-- ---------------------------------------------------------------------------
-- Platform channel registry
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.platform_chat_channels (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_number  bigint NOT NULL,
  slug            text NOT NULL,
  name            text NOT NULL,
  description     text NOT NULL DEFAULT '',
  enabled         boolean NOT NULL DEFAULT true,
  archived_at     timestamptz NULL,
  guest_allowed   boolean NOT NULL DEFAULT false,
  sort_order      integer NOT NULL DEFAULT 0,
  channel_kind    text NOT NULL DEFAULT 'admin'
    CHECK (channel_kind IN ('system', 'admin')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT platform_chat_channels_channel_number_key UNIQUE (channel_number),
  CONSTRAINT platform_chat_channels_slug_key UNIQUE (slug),
  CONSTRAINT platform_chat_channels_slug_format_chk
    CHECK (slug ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
  CONSTRAINT platform_chat_channels_system_slug_chk
    CHECK (channel_kind <> 'system' OR slug IN ('yaarzo-global', 'games')),
  CONSTRAINT platform_chat_channels_archive_state_chk
    CHECK (NOT enabled OR archived_at IS NULL)
);

CREATE INDEX IF NOT EXISTS platform_chat_channels_nav_idx
  ON public.platform_chat_channels (sort_order, channel_number)
  WHERE enabled AND archived_at IS NULL;

-- ---------------------------------------------------------------------------
-- Bot assignments (foundation; runtime bot behavior unchanged in 3B-1)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.platform_channel_bots (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id  uuid NOT NULL REFERENCES public.platform_chat_channels(id) ON DELETE RESTRICT,
  bot_key     text NOT NULL,
  enabled     boolean NOT NULL DEFAULT true,
  config      jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT platform_channel_bots_unique UNIQUE (channel_id, bot_key)
);

CREATE INDEX IF NOT EXISTS platform_channel_bots_channel_enabled_idx
  ON public.platform_channel_bots (channel_id)
  WHERE enabled;

-- ---------------------------------------------------------------------------
-- Slug validation (shared by triggers and RPCs)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_uuid_text(_value text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT _value ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';
$$;

-- Keep reserved route list aligned with src/lib/reserved-routes.ts (plus chat namespaces).
CREATE OR REPLACE FUNCTION public.is_valid_platform_channel_slug(
  _slug text,
  _channel_kind text DEFAULT 'admin'
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
DECLARE
  s text := lower(trim(coalesce(_slug, '')));
  kind text := lower(trim(coalesce(_channel_kind, 'admin')));
  reserved_routes text[] := ARRAY[
    'admin','api','feed','games','rooms','chatroom','chatrooms','messages','profile','profiles',
    'settings','friends','find-friends','notifications','login','register','signup','logout','auth',
    'account','achievements','leaderboard','reset-password','welcome','banned','confessions','feedback',
    'u','p','assets','static','public','manifest','robots','sitemap','favicon','root','index','reels',
    'pages','groups','installer','setup-wizard','pricing','wallet','deploy','radio','trust','heropage',
    'community','communities','competitions','battle-hub','broadcaster','gamification','invite',
    'live-arena','dm','trio','gdm','lobby','watch','adm'
  ];
BEGIN
  IF s IS NULL OR s = '' THEN
    RETURN false;
  END IF;
  IF kind NOT IN ('system', 'admin') THEN
    RETURN false;
  END IF;
  IF s IN ('yaarzo-global', 'games') THEN
    RETURN kind = 'system';
  END IF;
  IF kind = 'system' THEN
    RETURN false;
  END IF;
  IF s !~ '^[a-z0-9][a-z0-9_-]{0,63}$' THEN
    RETURN false;
  END IF;
  IF public.is_uuid_text(s) THEN
    RETURN false;
  END IF;
  IF s = 'dm' OR s LIKE 'dm:%' OR s LIKE 'dm-%'
     OR s = 'trio' OR s LIKE 'trio:%' OR s LIKE 'trio-%'
     OR s = 'gdm' OR s LIKE 'gdm:%' OR s LIKE 'gdm-%'
     OR s = 'watch' OR s LIKE 'watch:%' OR s LIKE 'watch-%'
     OR s = 'lobby' THEN
    RETURN false;
  END IF;
  IF s = ANY(reserved_routes) THEN
    RETURN false;
  END IF;
  IF EXISTS (SELECT 1 FROM public.platform_chat_channels c WHERE c.slug = s) THEN
    RETURN false;
  END IF;
  RETURN true;
END;
$$;

-- ---------------------------------------------------------------------------
-- Slug + immutable guards
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.platform_chat_channels_guard_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_valid_platform_channel_slug(NEW.slug, NEW.channel_kind) THEN
    RAISE EXCEPTION 'invalid platform channel slug: %', NEW.slug;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_platform_chat_channels_guard_insert ON public.platform_chat_channels;
CREATE TRIGGER trg_platform_chat_channels_guard_insert
  BEFORE INSERT ON public.platform_chat_channels
  FOR EACH ROW
  EXECUTE FUNCTION public.platform_chat_channels_guard_insert();

CREATE OR REPLACE FUNCTION public.platform_chat_channels_guard_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF OLD.channel_number IS DISTINCT FROM NEW.channel_number THEN
    RAISE EXCEPTION 'channel_number is immutable';
  END IF;
  IF OLD.slug IS DISTINCT FROM NEW.slug THEN
    RAISE EXCEPTION 'channel slug is immutable';
  END IF;
  IF OLD.channel_kind IS DISTINCT FROM NEW.channel_kind THEN
    RAISE EXCEPTION 'channel_kind is immutable';
  END IF;
  IF OLD.channel_kind = 'system' AND (
    NEW.enabled IS DISTINCT FROM OLD.enabled
    OR NEW.archived_at IS DISTINCT FROM OLD.archived_at
  ) THEN
    RAISE EXCEPTION 'system channels cannot be disabled or archived';
  END IF;
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_platform_chat_channels_guard_update ON public.platform_chat_channels;
CREATE TRIGGER trg_platform_chat_channels_guard_update
  BEFORE UPDATE ON public.platform_chat_channels
  FOR EACH ROW
  EXECUTE FUNCTION public.platform_chat_channels_guard_update();

CREATE OR REPLACE FUNCTION public.platform_chat_channels_guard_delete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF OLD.channel_kind = 'system' THEN
    RAISE EXCEPTION 'system channels cannot be deleted';
  END IF;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_platform_chat_channels_guard_delete ON public.platform_chat_channels;
CREATE TRIGGER trg_platform_chat_channels_guard_delete
  BEFORE DELETE ON public.platform_chat_channels
  FOR EACH ROW
  EXECUTE FUNCTION public.platform_chat_channels_guard_delete();

CREATE OR REPLACE FUNCTION public.platform_channel_bots_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_platform_channel_bots_updated_at ON public.platform_channel_bots;
CREATE TRIGGER trg_platform_channel_bots_updated_at
  BEFORE UPDATE ON public.platform_channel_bots
  FOR EACH ROW
  EXECUTE FUNCTION public.platform_channel_bots_set_updated_at();

-- ---------------------------------------------------------------------------
-- Server-side channel number allocation
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.allocate_platform_channel_number()
RETURNS bigint
LANGUAGE sql
VOLATILE
SET search_path = public
AS $$
  INSERT INTO public.platform_chat_channel_number_alloc DEFAULT VALUES
  RETURNING channel_number;
$$;

REVOKE ALL ON FUNCTION public.allocate_platform_channel_number() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.allocate_platform_channel_number() TO service_role;

-- ---------------------------------------------------------------------------
-- Seed system channels #1 Global, #2 Games (idempotent)
-- ---------------------------------------------------------------------------
INSERT INTO public.platform_chat_channels (
  channel_number, slug, name, description, enabled, guest_allowed, sort_order, channel_kind
)
VALUES
  (1, 'yaarzo-global', 'Global', 'Yaarzo public lobby', true, true, 0, 'system'),
  (2, 'games', 'Games', 'Game commands and bots', true, false, 10, 'system')
ON CONFLICT (channel_number) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  guest_allowed = EXCLUDED.guest_allowed,
  sort_order = EXCLUDED.sort_order,
  enabled = true,
  archived_at = NULL,
  updated_at = now();

-- Seed bot assignments from existing catalog keys only.
INSERT INTO public.platform_channel_bots (channel_id, bot_key, enabled, sort_order)
SELECT c.id, seed.bot_key, true, seed.sort_order
FROM public.platform_chat_channels c
JOIN (
  VALUES
    ('yaarzo-global', 'bot-spam', 0),
    ('yaarzo-global', 'bot-echo', 1),
    ('games', 'bot-gamebot', 0),
    ('games', 'bot-dig', 1),
    ('games', 'bot-fish', 2),
    ('games', 'bot-wine', 3),
    ('games', 'bot-pixel', 4),
    ('games', 'bot-nova', 5),
    ('games', 'bot-ryze', 6)
) AS seed(channel_slug, bot_key, sort_order)
  ON c.slug = seed.channel_slug
ON CONFLICT (channel_id, bot_key) DO UPDATE
SET enabled = EXCLUDED.enabled, sort_order = EXCLUDED.sort_order, updated_at = now();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.platform_chat_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_channel_bots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read active platform channels" ON public.platform_chat_channels;
CREATE POLICY "Public read active platform channels"
  ON public.platform_chat_channels
  FOR SELECT
  TO anon, authenticated
  USING (enabled AND archived_at IS NULL);

DROP POLICY IF EXISTS "Admins manage platform channels" ON public.platform_chat_channels;
CREATE POLICY "Admins manage platform channels"
  ON public.platform_chat_channels
  FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Public read bots for active platform channels" ON public.platform_channel_bots;
CREATE POLICY "Public read bots for active platform channels"
  ON public.platform_channel_bots
  FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.platform_chat_channels c
      WHERE c.id = platform_channel_bots.channel_id
        AND c.enabled
        AND c.archived_at IS NULL
    )
  );

DROP POLICY IF EXISTS "Admins manage platform channel bots" ON public.platform_channel_bots;
CREATE POLICY "Admins manage platform channel bots"
  ON public.platform_channel_bots
  FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

GRANT SELECT ON public.platform_chat_channels TO anon, authenticated;
GRANT SELECT ON public.platform_channel_bots TO anon, authenticated;
GRANT ALL ON public.platform_chat_channels TO service_role;
GRANT ALL ON public.platform_channel_bots TO service_role;
GRANT ALL ON public.platform_chat_channel_number_alloc TO service_role;
